[quote.epigraph, , 1 Thess. 5:21]
____
Prove all things; hold fast that which is good.
____

== Memoir of Samuel Crisp

Samuel Crisp, previous to his joining the Society of Friends, resided in Norfolk.
He was educated at College,
and took the order of deacon in the church of England (so called);
after which he officiated as a parish curate, also for a very short time,
as chaplain in a private family.

In the year 1700, being then resident in London, and about thirty years of age,
he was convinced of the truth, as professed by Friends,
in the manner described in his first letter below.
Soon afterwards he was engaged as an assistant to Richard Scoryer,
a Friend who kept a large boarding-school at Wandsworth.
In this situation he did not remain long,
and subsequently opened a school on his own account, at Stepney, near London.

From a work of his entitled [.book-title]#The Present State of Quakerism in England#,
we obtain the following particulars and remarks,
relative to Samuel Crisp`'s withdrawing from the communion of the established church,
and the stations he occupied therein:

"`As to my leaving the church of England,
God is my witness I did it in pure obedience to the convictions of my own mind;
and the peace which I have often felt returned into my bosom is more than I can express.
I have had a great and abundant reward from the Lord for what I have done in this matter.
I desire to fear God,
and am heartily sorry that I have spent so much time in
the vanities and impertinences of this sinful world;
taking things upon trust, swayed by temporal interests,
and following the prejudices of my education.
It is true I was in the order only of deacon,
and I bless God that I went no farther in such orders.
Then I pretended to preach, and could patch together an hour`'s discourse,
with something that I got from others, and something that I had read from the Bible,
filling up the vacancy with the dark conceivings of my own brain--and this was my gospel.
I could talk much of Christ, and heaven and hell, and extolled the Scriptures highly,
which were nevertheless a sealed book to me; for though I read them often,
both in public and private, yet my mind being outward,
and not waiting in silence upon that Holy Spirit that gave them forth,
I knew not the Scriptures nor the power of God:
so then the power of death and darkness ruled in me.`"

"`I had care of souls, (as they call it,) but was a physician of no value, I knew,
indeed, that I had served my time at the university, as apprentices do to a trade;
and that I had passed the examination and the ceremony
of ordination--and I thought this would do;
but as for any immediate call or appointment of God to the work of the ministry,
I knew nothing of it.
I had the care of two parishes committed to me by the bishop of the diocese,
but had never any call from God to go and preach to that people.
So I was like those prophets Jeremiah speaks of, in chapter 23,
who ran before they were sent, and therefore they could not profit the people at all.
I was a superstitious bigot--a poor dark creature--a hireling, blind leader of the blind.
I expected thirty pounds a year for preaching--that was my wages;
and if any should question my commission, I knew I had a little piece of paper to show,
which I called my orders, if that would satisfy them;
so brutish was I in my understanding.`"

"`And yet God did not leave Himself without a witness;
for in the midst of all this darkness and ignorance I
can truly say there was a measure of sincerity in me,
and good desires, and earnest cries and breathings were oftentimes raised in me,
that I might know the Lord and serve Him, and see His glory, and witness peace and joy,
and health and rest, and salvation to my soul, before I went off the stage of this world;
that so I might live with Him in that world which never shall have an end,
when time here shall be no more.
And God was not unmindful of the travail of His own seed in that day;
for blessed be His name, He heard the groanings of it under a great deal of rubbish,
and He revealed His Son in me,
at the brightness of whose appearance the clouds
are scattered and the shadows flee away.`"

"`May the sense of His goodness and tender mercy never depart from me,
so long as I have an hour to live, or a minute to breathe in this world.
Even to the same God that had compassion on Israel of old,
when they sojourned in a strange land,
where the Egyptians and Pharaoh oppressed them with much cruel
and hard bondage--to that God I ascribe my deliverance,
who alone is worthy to be praised,
magnified and adored by all who make mention of His name.
He remembered us when we were in trouble, and anguish, and deep affliction;
being scattered upon the dark and barren mountains, as sheep without a shepherd,
wandering from mountain to hill,
from one form and empty profession of religion to another; even there did He find us,
and His eye pitied us, and He said to the dry bones,
'`Live;`' for His mercy endures for ever.`"

Samuel Crisp`'s office as chaplain, (in which it seems he continued but ten days),
proved particularly irksome and unsatisfactory;
and it is probable that the circumstances connected with it,
strengthened in no small degree his desire to be disengaged
from the forms and ceremonies in which he had been educated.
On alluding to his situation in that capacity, he states,
that he has had to wait three or four hours at a time,
to know when the family would go to prayers;
and that his task was not finished when the prayers were ended,
as he was expected to wait, to be ready when called for,
in an adjoining room where servants and others were often passing, and company coming in;
and that he was sometimes thus kept in waiting from morning till night.

As he had occasion for some employment by which to procure a livelihood,
such inconveniences as these would probably have been borne
till an appointment less wearisome presented itself,
if he could have continued here and at the same time have enjoyed peace of mind:
but he writes:

"`I left my chaplain`'s place purely upon a foot of conscience;
the luster of mammon could not keep me there.
And this was some months before I came amongst the people called Quakers,
or had the least thoughts that way.
I lived some time privately in London, inquiring after the best things.
There was then a great noise about the Quakers,
and George Keith (who was just then ordained deacon) was the talk of the town.
So meeting one day with Robert Barclay`'s works in a bookseller`'s shop,
and understanding that he was a Quaker, and an eminent writer amongst them,
I had a great desire to read them; which I did in the fear of God,
and with a humble mind.
I was thereby so fully convinced of the truth of the Quakers`' principles,
(notwithstanding the clamor of the world against them), that from that day to this,
I have never once communicated in the church of England.
And though I was then destitute of any outward business,
yet I did not doubt but the Lord would some way
provide me a competent subsistence in this world,
which was all I desired.
This accordingly came to pass;
for within a few weeks I was recommended to Wandsworth school,
Richard Scoryer being then in need of a teacher.

However, right upon my convincement,
two things offered to draw me back again into the world: one was,
an opportunity to read prayers in an apothecary`'s house in Huntingdon; and the other,
to be chaplain to one called the Lady Molesworth, as I remember.
Here was some prospect of preferment, and it came before I heard of Wandsworth school,
or knew any thing of it.
So that if I had been so greedy of mammon as some would seem to represent me,
I might have smothered my convictions and turned back into Egypt again.
But blessed be God, who preserved me in that day, and kept me low before Him!
I trusted to His kind providence, who knew the sincerity of my heart;
and I chose rather to be poor and destitute with a good conscience,
than to have all the riches and honors of the world without it.
I had found the pearl of great price, and I knew I must sell all to purchase it.
Truth was my greatest treasure; that was my chiefest joy.
"`For,`" as the apostle says, "`our rejoicing is this, the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom, but by the grace of God,
we have conducted ourselves in the world.`"

This brief Memoir of Samuel Crisp, considered in connection with the sincerity, humility,
and genuine piety which his letters exhibit,
shows that he had begun to build on the one sure Foundation,
and that he seemed likely to become a truly serviceable member in the church.
But any hopes of this kind that had been cherished by his contemporary friends,
were only realized to a very limited extent,
since it pleased the All-wise Disposer of events to cut short the thread of his life.
He died of the small-pox, at Stepney aforesaid, on the 7th of the Fourth month, 1704,
aged 34 years.
