== Letters of Samuel Crisp

[.centered]
=== Letter I.

I received a letter from you, the week before last, which was sent by your uncle Bolton:
there were a great many kind expressions in it, and in your sister Clopton`'s likewise.
I acknowledge myself much obliged to you both, and to the whole family,
for many repeated kindnesses; and if my school had not engrossed so much of my time,
I would have taken opportunity to answer my dear friend`'s letter before now,
and upon that account my delay will be the more excusable.

The news you have heard of my late change is really true--I cannot conceal it,
for it is what I glory in--neither was it any prospect
of temporal advantage that induced me to it,
but a sincere love to the truth, and a pure regard to my own soul.
Neither can I be sufficiently thankful to God,
that He has let me live to this glorious day,
and not cut me off in the midst of my sins and provocations against Him.
He is long-suffering to us, not willing that any should perish,
but that all should come to repentance.
He has brought me off from the forms and shadows of religion, and let me see,
in a more illustrious manner, what is the life and substance of it,
as He found me in some degree faithful to that measure
of light and knowledge He had bestowed on me,
while I was in the communion of the church of England.
Therefore He was pleased of late, as I humbly waited upon Him,
to make known to me greater and deeper mysteries of His kingdom.
And I can truly say, that I find by daily experience,
as I keep low and retired unto that pure gift which He has planted within me,
things are more and more cleared up to me,
and the truth shines and prevails greatly over the kingdom of darkness.
And if I should now turn my back upon such manifestations as these,
and entangle myself again with the yoke of bondage,
surely I should grieve the Holy Spirit,
so that He might justly withdraw His kind operations,
and never return more to assist and comfort me.
For God is not mocked: religion is a very serious and weighty thing.
Repentance and salvation are not to be trifled with;
nor is turning to God to be put off till our own time, leisure, or convenience;
but we must love and cherish the least appearance of Christ,
not slighting or despising the day of small things,
but embrace the first opportunity of following Christ in any of His commands.
When He speaks, it is with such force and authority, that we cannot stand to cavil,
dispute, or ask questions;
for unless we will be so obstinate as to shut our eyes against the sun,
we must need confess to the truth of His doctrine, and presently fall in with it.

And, therefore,
when for several weeks I had lived more privately and retiredly in London,
than was usual, fasting twice or thrice in a week, and sometimes more,
spending my time in reading the Scriptures and in prayer to God,
this was a good preparation of my mind to receive the
truth which He was then about to make known to me.
I lamented the errors of my past life,
and was desirous to attain a more excellent degree of
holiness than I had discovered in the church of England.
In this religious retirement God knew the breathings of my soul, how sincere I was,
and how resigned to Him when alone.
I wanted Him to set me free, and to speak peace and comfort to my soul,
which was grieved and wearied with the burden of my sin.
For though I had strictly conformed myself to the
orders and ceremonies of the church of England,
and had kept myself from running into any great or scandalous enormities,
(the fear of the Almighty preserving me),
yet still I had not that rest and satisfaction in
myself which I desired and greatly longed for.
I found when I had examined my state and condition towards God,
that things were not right with me.

As for sober and convincing conduct in the eye of the world,
I knew that was a very easy attainment.
Indeed, a good natural temper, with the advantage of a liberal education,
will quickly furnish a man with abilities for that;
so that he shall be looked upon as a saint, and very spiritual,
when perhaps still in chains of darkness, in the gall of bitterness,
and in the very bond of iniquity.
If this sort of righteousness would have done,
perhaps I might make as fair pretensions that way as some others; but, alas!
I quickly saw the emptiness and unsatisfactoriness of those things.
This is a covering that will not protect or hide us from the wrath of the Almighty,
when He comes to judgment.
It is not a man`'s natural temper, nor his education, that makes him a good Christian.
No, this is not the righteousness the gospel calls for,
nor is this the "`truth in the inward parts,`" which God requires.
The heart and affections must be cleansed and
purified before we can be acceptable to God;
therefore it was death to me to think of taking
up my rest in a formal pretense of holiness,
wherein I yet saw (to my grief) an abundance of people had wrapped themselves,
and slept securely and quietly, dreaming of the felicity of paradise,
as if heaven were now their own,
and they needed not trouble themselves any more about religion.
I could not entertain so dangerous an opinion as this;
for then I should be tempted to take up my rest by the way,
while I was still traveling towards the promised land.

I think I made a little progress in a holy life,
and through God`'s assistance I weakened some of my spiritual enemies
even while I lived in the communion of the national church.
I thank my God, I can truly say, while I used those prayers,
I did it with zeal and sincerity, in His fear and dread.
But still I ceased not my earnest supplication to Him in private,
that He would show me something more excellent;
that I might get a complete victory over all my lusts and passions,
and might perfect righteousness before Him.
For I found a great many sins and weaknesses daily attending me;
and though I made frequent resolutions to forsake those sins,
yet still the temptation was too strong for me;
so that I had often cause to complain with the apostle in the bitterness of my soul,
"`O wretched man that I am!
Who shall deliver me from the body of this death?`"
Who shall set me free, and give me strength to triumph over sin, the world,
and the devil, that I may in everything please God,
and there may not be the least thought, word or motion, gesture or action,
but what is exactly agreeable to His most holy will, as if I saw Him standing before me,
and as if I were to be judged by Him for the thought of my heart the next moment!
O divine life!
O seraphic soul!
O that I could always stand here!
For here is no reflection, no sorrow, no repentance;
but at God`'s right hand there is perfect peace and a river of unspeakable joy.
O that we might be like unto the life of Jesus,
and be thoroughly furnished unto every good word and work!
This was the frequent breathing of my soul to God when I was in the country,
but more especially after I had left my new preferment of a chaplain,
and took private lodgings in London.
In this retirement, I hope I may say without boasting, I was very devout and religious,
and found great comfort and refreshment in it from the Lord,
who let me see the beauty of holiness.
Indeed the sweetness that arises from a humbled, mortified life,
was then very pleasant to my taste,
and I rejoiced in it more than in all the delights and pleasures of the world.

And now it pleased God to show me,
that if I would indeed live strictly and holily as becomes the gospel,
then I must leave the communion of the church of England,
but I knew not yet which way to go, nor to what body of men I should join,
who were more orthodox and more consistent in their lives.
As for the Quakers (so called), I was so great a stranger to them,
that I had never read any of their books,
nor do I remember that ever I conversed with any
one man of that communion in my whole life.
I think there was one Quaker in Foxly, while I was curate there; but I never saw the man,
though I went several times to his house on purpose to talk with him,
and to bring him off from his mad and wild enthusiasm,
as I then ignorantly thought it to be.
As for their way, I knew it was everywhere spoken against.
Indeed, he that had a mind to appear more witty and ingenious than the rest,
would choose them for the subject of his profane jests and mockery;
and with this he makes sport, and entertains his company,
for a Quaker was but another name for a fool or a madman,
and was scarcely ever mentioned but with scorn and contempt.
As for mockery, I confess I was never any great friend to it.
But indeed, if all was true that was laid to the Quakers`' charge,
I thought they were some of the worst people that ever appeared in the world,
and wondered how they could call themselves Christians,
since I was told they denied the fundamental articles of the holy faith,
for which I ever bore the highest veneration and esteem.
And notwithstanding, I had always lived at the greatest distance from that people,
and was very zealous in the worship of the church of England,
and upon all occasions would speak very honorably of it.

While I lived in London, in that private, retired manner I was just now speaking of,
walking very humbly in the sight of God,
and having opportunity to reflect upon my past life,
as I had occasion to be one day at a bookseller`'s shop,
I happened to cast my eye on Barclay`'s works;
and having heard in the country that he was a man of great account among the Quakers,
I had a mind to see what their principles were,
and what defense they could make for themselves; for surely, thought I,
these people are not so silly and ridiculous, nor maintainers of such horrid opinions,
as the author of [.book-title]#The Snake,#^
footnote:[[.book-title]#The Snake in the Grass# was a slanderous anti-Quaker publication written by John Faldo.]
and some others would make us believe.
I took Barclay home with me, and I read him through in a week`'s time,
save a little treatise at the end, which finding to be very philosophical, I omitted.
I had soon read enough to convince me of my own
blindness and ignorance in the things of God.
There I found a light to break in upon my mind,
which did mightily refresh and comfort me in that poor, low,
and humbled state in which I then was; for indeed I was then,
and had been for a considerable time before, very hungry and thirsty after righteousness;
and therefore I received the truth with all readiness of mind.
It was like balm to my soul, and as showers of rain to the thirsty earth,
which is parched with heat and drought.
This author laid things down so plainly,
and proved them with such ingenuity and dexterity of learning,
and opened the Scriptures so clearly to me, that without standing to criticize, dispute,
raise argument or objection, or consulting with flesh and blood,
I presently resigned myself to God;
and weeping for joy that I had found so great a treasure,
I often thanked Him with tears in my eyes for so kind a visitation of His love,
that He was graciously pleased to look towards me when my soul cried after Him.
So, though before I was in great doubt and trouble of mind,
not knowing which way to direct myself,
yet now the sun broke out so powerfully upon me that the clouds were scattered.
I was now fully satisfied in my own mind which way I ought to go,
and to what body of people I should join myself.

So I immediately left the communion of the church of England,
and went to the Grace Church Street Meeting.
After I had read Barclay, I read some other books of that kind,
among which was an excellent piece, though in a small volume, called No Cross, No Crown.
Thus I continued reading and frequenting meetings for several weeks together,
but did not let any one soul know what I was about.
The first man I conversed with was George Whitehead,
and this was several weeks after I began to read Barclay, and frequent Friends`' meetings.
By him I was introduced into more acquaintance; and the farther I went,
the more I liked their plainness, and the decency and simplicity of their lives.
They do not use the ceremonies and salutations of the church of England,
but shake hands freely,
and converse together as brothers and sisters that are sprung of the same royal seed,
and made kings and priests unto God.
O the love,
the sweetness and tenderness of affection I have
seen among this people! "`By this,`" says Christ,
"`shall all men know that you are my disciples, if you have love one to another.`"
"`Put on therefore,`" says the apostle, "`as the elect of God, holy and beloved,
bowels of mercy, kindness, humbleness of mind, meekness, long-suffering.`"

Thus, my dear friend, I have given you an account of my proceeding on this affair.
As to my bodily state, if you desires to know what it is,
I may acquaint you that I have my health as well as ever,
and I bless God I have food and raiment sufficient for me,
so that I lack no outward thing.
Indeed, I have the necessities and conveniences of life;
so let us not burden ourselves with taking care for the vanities and superfluities of it.
Let us possess our vessels in sanctification and honor;
and even as we bring our minds into perfect subjection to the whole will of God,
so let us bring our bodies to the most simple and natural way of living.
Let us be content with the fewest things, never seeking to gratify our wanton appetites,
nor to follow the customs and humors of men,
but rather seek how we may so govern our earthly cares
and pleasures that we may bring most glory to God,
most health and peace to our own souls, and do most service to the Truth.
And if this be our aim,
certainly a very small portion of the things of this world will suffice us.
Seeing we are Christians,
we should therefore earnestly pursue those things which bring us nearest to God.
For whatever is more than a necessity, seems to be a burden to the soul,
which desires to breathe in a pure vessel,
that so it may have a living sense and relish of all blessings,
both of the superior and inferior worlds.

You know, my dear friend, that religion is a very serious thing.
Repentance is a great work,
and one precious immortal soul is of more worth than ten thousand perishing worlds,
with all their pomp and glory.
Therefore let us take courage, and be valiant for the truth upon the earth.
Let us not content ourselves with a name and profession of godliness,
but let us come to the life and power of it,
not becoming despondent of getting the victory.
We have a little strength for God;
let us be faithful to Him and He will give us more strength,
so that we shall see the enemy of our peace fall before us,
and nothing shall be impossible unto us.
I say, my friend,
let us be faithful to that measure of light and knowledge which God has given us,
to be profited and edified by it in a spiritual life.
And as God sees that we are diligent and faithful to
work with the strength we have received,
He will more and more enlighten us,
so that we shall see to the end of those forms and
shadows of religion wherein we had formerly lived.
But if He sees we are about to take up our rest in those shadows,
that we grow cold and indifferent in the pursuit of holiness,
running out into notions and speculations, and have more of a mind to dispute,
and to make a show of learning and subtlety than to lead a holy and devout life,
then it is just with God to leave us in a carnal and polluted state;
to continue yet but in the outward court,
where we may please ourselves with beholding the
beauty and ornaments of a worldly sanctuary,
and never witness the veil being taken away,
and being brought by the blood of Jesus into the holiest of all,
where alone there is true peace with God, and rest to the weary soul.
I could say much upon this subject, if time or leisure would give leave.

As for a particular answer to your letter, I have not time now to give it,
but desire for the present to let this general answer suffice.
And if you will consider things in their pure nature,
and not allow the prejudice of education to sway you,
but in fear and humility will search out the truth for yourself,
you will find that there needs no other answer
to your letter than what I have already given.
For by waiting upon God, and diligently seeking Him,
you will find an answer to it in your own bosom; and this will be much more full, clear,
and satisfactory than I, or any other man living, can pretend to give you.
For truly I desire that you,
together with all the sincere-hearted in the church of England,
come to witness the almighty power of God to save and redeem them from every yoke:
and that they may clearly see to the end of those things which are abolished,
and come to the enjoyment of spiritual and heavenly things themselves.
Indeed, this is the daily prayer and deep travail of my soul, God knows.
Until I can be more particular, if you please you may communicate this to the others,
and let them know that I am well, and thank them for their kind letters.
Let us remember to pray for one another with all fervency,
that we may stand perfect in the whole will of God.
Amen, says my soul.

[.signed-section-closing]
I am your most affectionate friend and servant in Jesus,

[.signed-section-signature]
Samuel Crisp

[.centered]
=== Letter II.

[.salutation]
My dear friend,

I lately received a kind and brotherly letter from you,
for which I return you many thanks.
I am now in the communion of the people called Quakers;
and I have cause to bless God for this happy change of my life.
I am, through mercy, brought off from the shadow of religion,
and am pressing forward to get acquaintance with the quickening power, life,
and virtue of it, that I may be a Christian indeed,
and not in the name and profession only.
For a great while, I had talked and discoursed of holiness,
but did not understand what it was to walk with God, to live and dwell in Him.
Perhaps, indeed, some may think I made a fair show of piety when I was with you; but,
alas!
I was deeply sensible of my own faults and miscarriages; and I resolved,
through God`'s assistance,
to inquire after something more noble and excellent than I had discovered in that state.
And blessed be His name forever, God has answered the cry of my soul,
and let me see a people that are hated and despised by the world, but are dear to Him;
for He has revealed to them the mysteries of the kingdom;
He has carried them upon eagles`' wings, and cherished them as the apple of His eye.

As for me, I have been yet but in the outward court,
and far short of that truth and righteousness
that is taught and practiced among this people;
for they are come within the holiest of all.
Indeed, they are come into a near communion with God,
to behold the cherubims of glory that cover the mercy seat,
and to be fed with the true manna.
These are mysteries that are revealed unto the meek and lowly; but the haughty, insolent,
and profane cannot come near them, nor taste of the sweetness or comfort of them.
The formal, traditional sort of people of the world may talk of these things,
as they have heard them from others,
and in their sober moments may have some faint glimmerings that way;
but to have come to the real and inward enjoyment of them, they can no more claim,
than to work the greatest impossibilities.
Indeed all their wit, subtlety, and learning,
cannot reach high enough to handle of the word of life,
for it is known only to those who are content to forsake all,
and become fools for Christ.
These are in a good temper to receive and
cooperate with the influences of the Holy Spirit,
and have seen the emptiness and vanity of all those
things that are so much admired by the world.
The schools and universities, and learned doctors, and great rabbies,
have not profited me; they are departed from the Spirit of God,
and gone out into their own notions and speculations, thinking thereby to search out God,
and comprehend the truth.
Alas! the mysteries of the kingdom are far out of their reach in their carnal minds;
they weary themselves in vain, for the vulture`'s eye cannot pierce into these secrets.
All the great critics, scholars, and philosophers of the world, are fools in these things.
They are wearying themselves to find the deep things of our God,
studying and racking their heads,
tossing and tumbling to and fro like a wild bull in a net,
that knows not which way to disentangle himself--the more he struggles,
the weaker he grows and the faster he is bound.
So too, the more these vain talkers read, the more they write,
the more they cavil and dispute, the farther they are from God,
and the more they declare their hatred and enmity to the Spirit of Christ,
and to the simplicity of the gospel.

I have been, for a long time, weary of the folly and impertinency of these men,
and chiefly the celebrated "`fathers of the church,`" as they call them.
The councils and synods of old are now of very small account with me.
I am not ashamed to sit under the teachings of women and mechanics,
howsoever they may seem in the eye of the world.
Truly these now teach me more Christianity,
and instruct me more perfectly in a divine life, than all the studied,
elaborate sermons and discourses that ever I heard at the universities or since.
Their words are with power; yes, they are mightily assisted by the Spirit of God,
and speak with majesty and authority, and there is a native beauty, clearness,
and solidity of expression, that shines through their discourses,
which is sufficient to answer that groundless slander, namely,
that the Quakers`' preaching is nonsense, and nobody can understand them.
This I have heard often refuted by many living testimonies;
so that I do rather think them the best minds,
and the most ingenious people in the world;
for they employ their skills and learning in the fear of God, to His glory and service,
and to promote the true interest of mankind.

As for the common little jests, the wittiness, and vain showmanship of the age,
which I know the world has esteem for (and nothing will
please it but what abounds with such fooleries);
I say, if the Quakers be deficient in any of these, it is not for lack of abilities,
or because they have less wit than other men,
but because they have more prudence and wisdom to govern it.
That is the reason why they avoid such childish vanities,
which are so freely used and indulged in by others, to the great dishonor of God,
and the Christian religion.
Therefore because they do not seek to please a loose and shameless age,
and make people laugh and be merry, nor to entertain that carnal,
airy mind with pleasant stories, fine notions, and witty expressions of natural things;
from here it is that they have been shamefully misrepresented by the world,
as the most ignorant, blind,
and foolish people that ever made any profession of religion.

And yet this is the people to whom I have now joined myself in a sincere love to truth.
God knows, I glory more in this fellowship and acquaintance with these lambs of Christ,
than if I were related to the greatest kings, lords, and potentates upon the earth.
Oftentimes has my spirit been refreshed with theirs
when we have met together to wait upon God,
and my soul still longs and pants more and more to be filled with these divine comforts.
He is ready always to pour down blessings upon us,
if we would qualify ourselves for the reception of them;
if we would put away vain thoughts, which cloud and darken the mind,
and so hinder the favorable influences and irradiations of heaven.
And since it has pleased God to visit me of late,
and to make known to me excellent things in righteousness,
He alone is to have the praise and glory of all;
and now I freely resign myself to the ways of the blessed Spirit.

Now let the truth prosper!
Let it run and be glorified in the earth!
Let it shine out in its full luster, to the terror and confusion of all its enemies,
and to the reviving of the souls of the hungry and thirsty, who are ready to faint,
waiting for and expecting the consolation of Israel,
until the time of refreshment comes from the presence of the Lord.
Truly He will open a fountain for Judah and Jerusalem,
so that rivers shall run in dry places; there will He speak peace to His people.
And after they have sat silent a little while in the dust,
suffering patiently the chastening rod of His love to pass over them,
He shall then comfort the daughter of Zion, and say, "`Arise, you afflicted,
and weep and mourn no more, but put on your beautiful garments, O Jerusalem!
Raise your head, uncover your face, and gird up your loins with strength;
see the day break, and the morning spread itself upon the mountains;
now the sorrowful nights of affliction have passed over,
the clouds are scattered and gone, the sun is risen in its brightness,
and now joy and peace shall be multiplied.
In a little wrath I hid my face from you for a moment,
but with everlasting kindness will I have mercy on you, says the Lord your Redeemer.`"

O let us wait, in humility of soul and tenderness of heart before the Lord,
that we may witness this great change and salvation wrought in us and for us,
so that the Scripture may be no more a sealed book to us,
but that we may feel the precious truth there recorded,
to be fulfilled in our own particulars.
Then we shall never be weary of praying, and reading the Holy Scriptures.
We shall never be unwilling to come into God`'s presence; for His love,
and the sweetness of His ointment,
will draw and allure us to dwell always under His canopy,
that we may feel life and power to flow from Him,
who is the ocean that supplies all the needs of the children of men.
And how shall we come to taste that heavenly banquet which He has prepared for us,
that we may eat and drink at His table, and that our souls may delight in fatness--I say,
how shall we attain to this, but by a strict and mortified life?
Certainly the more we retire from worldly joys,
and empty ourselves of earthly comforts and false delights,
the fitter we shall be to receive those that are spiritual and heavenly;
and not only to receive and rejoice in them for a time,
but to live and dwell in them forever.
For this is the life of Jesus; and here the kingdom of God reigns in the heart and soul,
by which it is changed from glory to glory, even as by the Spirit of the Lord.

And now I would ask all the wise and prudent, all the rich,
all the noble and learned men of the world, what they think of these things?
Whether such things are to be learned in their courts and palaces?
Or whether any of the great scholars and universities in Christendom
can furnish us with such a system of divinity as this?
No; they hate it and despise it; and instead of a sober answer to my question,
they return scoffs and contempt.
"`This is rubbish`" they say,--"`an idle dream,
and a forged delusion of his own brain`" and a great many more
opprobrious names they have for such inquiries as these.
Sometimes perhaps they will soften their expressions with a hypocritical show,
pretending to pity me, calling it an unhappy effect of melancholy,
and too much retirement from the world.
This some think to be too much condescension,
and that I ought to think myself grateful to them for giving it so mild a character;
for at other times they deal more sharply, and say confidently that it is madness,
delusion, witchcraft, and diabolical enthusiasm.
But I am content to lie under all these odious imputations from the world,
knowing very well, that better men than I have suffered the same things before me,
and do at this present time.
As for my enemies, I can truly say, I thank God I can pity them and pray for them:
they do not hurt me, but themselves.

And now my dear friend, before I conclude,
allow me a little to speak of your present circumstances; for as God knows,
my heart yearns towards you in the tender love of Jesus.
I suppose you are now where I left you, namely, with the lord Richardson, (so called),
in the capacity of a chaplain--an office which I have had a little experience of myself,
since I last saw you, but was quickly so weary of that servile yoke,
so unworthy of that holy function I bore,
that in ten days`' time I quitted my new preferment,
and left it more free than ever I undertook it.
What peace or satisfaction you can have in such kind of employment, I know not;
for my part I could find none;
my soul was grieved and burdened every day with seeing and hearing their evil deeds,
beholding their vanities and excesses.
Indeed, this was a sword to my soul and spirit, it wounded me very deep;
and I do solemnly profess, I had rather beg my bread from door to door,
than to live in the like bondage again,
where I must be obliged to such ceremonies and
formalities,--to flatter men in their sins;
to cry, "`peace, peace,`" and to sew pillows under the armholes of delicate people,
who can never bear the least check or frown;
but expect the mercenary priest should always laugh or smile in their faces,
even when he sees plainly they are going to hell and destruction.
And yet I must tell you,
the family I was in was looked upon as one of the most sober and consistent,
as the world goes now.
And I must needs say, I did not leave them for any drinking, gaming, or swearing,
that I perceived among them.
As to all these filthy, scandalous practices, as far as I could see, they were blameless;
yet I saw their hearts were not right,
for they were lovers of pleasure more than lovers of God; and you know that he or they,
let them be great or small, if they live in pleasures, grow fat,
and careless towards Christ; such persons are dead while they live.
I say, whatever their faith, or principles, or professions may be,
yet in true religion they are dead.

I shall say no more, but hasten to a conclusion.
If you desire a particular account of my convincement,
you may see it in a letter I wrote lately to Richard Lake jr.,
wherein I gave him a fair and true relation of my proceedings in that matter,
what steps I took, and how God did graciously assist me,
when He had raised in me sincere desires and inquiries after truth and holiness.
Dear friend, I have no more at present,
but to let you know that I do most heartily pray for you,
that you may consider things without prejudice,
and not allow any of the temptations and allurements of
the world to draw your mind from God,
and to hinder you in your pursuit of holiness.
He that loves father or mother, brother or sister,
or any of the endearments of this world, more than Christ, is not worthy of Him.
But if you will come into communion with Christ,
and follow the guidance of His light and Spirit,
O what a blessed and happy rest you shall find to your soul!
O what rivers of living waters will spring up in you, of which you may drink freely,
and praise God for all His mercies and benefits.

That you may indeed come to such spiritual enjoyments and refreshments as these,
is the sincere desire of your loving and affectionate friend,

[.signed-section-signature]
Samuel Crisp
