[quote.epigraph, , 1 Thess. 5:21]
____
Prove all things; hold fast that which is good.
____

== Life and Letters of Samuel Crisp

=== Memoir of Samuel Crisp

Samuel Crisp, previous to his joining the Society of Friends, resided in Norfolk.
He was educated at college,
and took the order of deacon in the Church of England (so called);
after which he officiated as a parish curate,
and also for a very short time as chaplain in a private family.

In the year 1700, being then a resident in London, and about thirty years of age,
he was convinced of the truth as professed by Friends,
in the manner described in his first letter below.
Soon afterwards he was engaged as an assistant to Richard Scoryer,
a Friend who kept a large boarding-school at Wandsworth.
In this situation he did not remain long,
and subsequently opened a school on his own account, at Stepney, near London.

From a work of his entitled [.book-title]#A Vindication of the People Called Quakers,#
we obtain the following particulars and remarks,
relative to his withdrawing from the communion of the established church,
and the stations he occupied therein:

[.embedded-content-document]
--

As to my leaving the Church of England,
God is my witness I did it in pure obedience to the convictions of my own mind;
and the peace which I have often felt returned into my bosom is more than I can express.
I have had a great and abundant reward from the Lord for what I have done in this matter.
I desire to fear God,
and am heartily sorry that I have spent so much time
in the vanities and trifles of this sinful world;
taking things upon trust, being swayed by temporal interests,
and following the prejudices of my upbringing.

It is true I was in the order only of deacon,
and I bless God that I went no further in such orders.
I then pretended to preach,
and could patch together an hour`'s discourse with something that I got from others,
and something that I had read from the Bible,
filling up the vacancy with the dark conceivings of my own brain--and this was my gospel.
I could talk much of Christ, and heaven and hell, and extolled the Scriptures highly,
which were nevertheless a sealed book to me; for though I read them often,
both in public and private, yet my mind being outward,
and not waiting in silence upon that Holy Spirit that gave them forth,
I knew not the Scriptures nor the power of God.
Thus the power of death and darkness then ruled in me.

I had that care of souls (as they call it), but was a physician of no value.
I knew, indeed, that I had served my time at the university,
as apprentices do to a trade;
and that I had passed the examination and the ceremony
of ordination--and I thought this would do;
but as for any immediate call or appointment of God to the work of the ministry,
I knew nothing of it.
I had the care of two parishes committed to me by the bishop of the diocese,
but had never any call from God to go and preach to that people.
So I was like those prophets Jeremiah speaks of, chapter 23:21,
who ran before they were sent, and therefore they could not profit the people at all.
Truly, I was a superstitious bigot--a poor dark creature--a
hireling--a blind leader of the blind.
I expected thirty pounds a year for preaching--that was my wages;
and so brutish was I in my understanding, that if any should question my commission,
I knew I had a little piece of paper to show them, which I called my orders,
if that would satisfy them.

And yet God did not leave himself without a witness;
for in the midst of all this darkness and ignorance,
I can truly say there was a measure of sincerity in me.
Good desires and earnest cries and breathings were oftentimes raised
in me that I might truly know the Lord and serve Him,
and see His glory,
and witness peace and joy and health and rest and salvation to my soul,
before I went off the stage of this world,
that so I might live with Him in that world which never shall have an end,
when time here shall be no more.
And God was not unmindful of the travail of His own seed in that day;
for blessed be His name, He heard the groanings of it under a great deal of rubbish,
and He revealed His Son in me,
at the brightness of whose appearance the clouds are scattered and the shadows flee away.
May the sense of His goodness and tender mercy never depart from me,
so long as I have an hour to live, or a minute to breathe in this world.
Even to the same God that had compassion on Israel of old,
when they sojourned in a strange land,
where the Egyptians and Pharaoh oppressed them with much
cruel and hard bondage--to that God I ascribe my deliverance,
who alone is worthy to be praised,
magnified and adored by all who make mention of His name.
He remembered us when we were in trouble and anguish and deep affliction,
being scattered upon the dark and barren mountains as sheep without a shepherd;
wandering from mountain to hill,
from one form and empty profession of religion to another.
Even there did He find us, and His eye pitied us, and He said to the dry bones,
"`Live;`" for His mercy endures forever.

--

Samuel Crisp`'s office as chaplain in a private family (in which it seems
he continued only ten days) proved particularly irksome and unsatisfactory;
and it is probable that the circumstances connected with it strengthened,
in no small degree,
his desire to be disengaged from the forms and ceremonies in which he had been educated.
On alluding to his situation in that capacity,
he states that he has had to wait three or four hours at
a time to know when the family desired to go to prayers;
and that his task was not finished when the prayers were ended,
as he was expected to wait and be ready when called for from an
adjoining room where servants and others were often passing;
and that he was sometimes thus kept in waiting from morning till night.
Such inconveniences as these would probably have been borne
with till an appointment less wearisome presented,
could he have continued here and at the same time have enjoyed peace of mind;
but he writes:

[.embedded-content-document]
--

I left my chaplain`'s place purely upon a principle of conscience;
the luster of mammon could not keep me there,
and this was some months before I came amongst the people called Quakers,
or had the least thoughts that way.
I lived some time privately in London, inquiring after the best things.
There was then a great noise about the Quakers, and George Keith^
footnote:[George Keith was a prominent Scottish member of the early Society of Friends,
who spoke and wrote much in defense of Quaker principles and doctrines,
and even suffered imprisonment for his testimony for the truth.
Sadly, later in life,
because of a restless and ambitious spirit that aspired to preeminence
in the Society (George Fox having died in 1690),
Keith eventually broke out into open opposition, first against specific individuals,
and eventually against the entire Society of Friends.
After first attempting to set up his own separate religious society,
he at last joined in communion with the Church of England,
was ordained a priest by the bishop of London,
and ended his days as a persecutor of the very religious society he once defended.]
(who was just then ordained deacon) was the talk of the town.
So meeting one day with Robert Barclay`'s works in a bookseller`'s shop,
and understanding that he was a Quaker, and an eminent writer amongst them,
I had a great desire to read them.
This I did in the fear of God, and with a humble mind,
and was thereby so fully convinced of the truth of the Quakers`'
principles (notwithstanding the clamor of the world against them),
that from that day to this, I have never once returned to the Church of England.
And though I was then destitute of any outward business,
yet I did not doubt but the Lord would some way provide
me with a competent subsistence in this world,
which was all I desired--and this accordingly came to pass;
for within a few weeks I was recommended to Wandsworth school,
Richard Scoryer being then in need of an assistant.

But, just following my convincement of the truth,
two things offered to draw me back again into the world.
One was an offer to read prayers in an apothecary`'s house in Huntingdon; and the other,
to be chaplain to one called the Lady Molesworth, as I remember.
In both of these there was some prospect of preferment,
and this was before I heard of Wandsworth school, or knew anything of it.
So that if I had been so greedy of mammon as some would seem to represent me,
I might have smothered my convictions and turned back into Egypt again.
But blessed be God, who preserved me in that day, and kept me bowed low before Him!
I trusted to His kind providence, who knew the sincerity of my heart;
and I chose rather to be poor and destitute with a good conscience
than to have all the riches and honors of the world without it.
I had found the pearl of great price, and I knew I must sell all to purchase it.
Truth was my greatest treasure; that was my chiefest joy.
"`For,`" as the apostle says, "`our rejoicing is this, the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom, but by the grace of God,
we have conducted ourselves in the world.`"

--

[.asterism]
'''

=== Letters of Samuel Crisp

+++[+++The three following Letters of Samuel Crisp were written about the year 1702;
the first and second on the occasion of his withdrawing
from the Church of England to join the Society of Friends.
These two have been published several times together as a pamphlet.
The third letter, although very short, is not without its value, showing, as it does,
the writer`'s conviction that his having so far yielded to apprehended
duty in uniting in religious fellowship with Friends,
furnished no ground for relaxing his watchfulness and diligence in the Christian warfare.]

[.centered]
==== Letter I.

I received a letter from you the week before last, which was sent by your uncle Bolton;
there were a great many kind expressions in it, and in your sister Clopton`'s as well.
I acknowledge myself much obliged to you both, and to the whole family,
for many repeated kindnesses;
and if the care of my school had not engrossed so much of my time,
I would have taken opportunity to answer my dear friend`'s letter before now,
and upon that account my delay will be the more excusable.

The news you have heard of my late change is really true--I cannot conceal it,
for it is what I glory in--nor was it any prospect
of temporal advantage that induced me to it,
but a sincere love to the truth, and a pure regard to my own soul.
Neither can I be sufficiently thankful to God that
He has let me live to see this glorious day,
and not cut me off in the midst of my sins and provocations against Him.
He is long-suffering to us, not willing that any should perish,
but that all should come to repentance.
He has brought me off from the forms and shadows of religion, and let me see,
in a more illustrious manner, what is the life and substance of it,
as He found me in some degree faithful to that measure of light and knowledge
He had bestowed on me while I was in the communion of the Church of England.
Therefore He was pleased of late, as I humbly waited upon Him,
to make known to me greater and deeper mysteries of His kingdom.
And I can truly say,
that I find by daily experience (as I keep low and retired
unto that pure gift which He has planted within me),
things are more and more cleared up to me,
and the truth shines and prevails greatly over the kingdom of darkness;
and if I should now turn my back upon such manifestations as these,
and entangle myself again with the yoke of bondage,
surely I should grieve the Holy Spirit,
so that He might justly withdraw His kind operations,
and never more return to assist and comfort me.
For God is not mocked; religion is a very serious and weighty thing.
Repentance and salvation are not to be trifled with;
nor is turning to God to be put off till our own time, leisure, or convenience.
But we must love and cherish the least appearance of Christ,
not slighting or despising the day of small things,
but embracing the first opportunity of following Christ in any of His commands.
When He speaks, it is with such force and authority that we cannot stand to cavil,
dispute, or ask questions;
for unless we will be so obstinate as to shut our eyes against the sun,
we must necessarily confess to the truth of His doctrine, and presently fall in with it.

Therefore,
when for several weeks I had lived more privately and retiredly in London than was usual,
fasting twice or three times in a week, and sometimes more,
spending my time in reading the Scriptures and in prayer to God,
this was a good preparation for my mind to receive the truth
which He was then about to make known to me.
I lamented the errors of my past life,
and was desirous to attain a more excellent degree
of holiness than I had found in the Church of England.
In this religious retirement, God knew the breathings of my soul,
and how sincere I was and resigned to Him when alone.
I needed Him to set me free, and to speak peace and comfort to my soul,
which was grieved and wearied with the burden of my sin.
For though I had strictly conformed myself to the
orders and ceremonies of the Church of England,
and had kept myself from running into any great or scandalous
sins (the fear of the Almighty preserving me),
yet still I had not that rest and satisfaction in
myself which I desired and greatly longed for.
I found when I had examined my state and condition towards God,
that things were not right with me.

As for having a sober and convincing conduct in the eyes of the world,
I knew that was a very easy attainment.
A good natural temper, with the advantage of a liberal education,
will quickly furnish a man with abilities for that,
so that he may be looked upon as a saint, and very spiritual,
when he is perhaps still in chains of darkness, in the gall of bitterness,
and in the very bond of iniquity.
If this sort of righteousness would have done,
perhaps I might have made as fair pretensions in that way as some others; but alas,
I quickly saw the emptiness and unsatisfactoriness of such things.
Truly,
this is a covering that will not protect or hide us from
the wrath of the Almighty when He comes to judgment.
It is not a man`'s natural temper, nor his education, that makes him a good Christian;
this is not the righteousness that the gospel calls for,
nor is it the "`truth in the inward parts,`"^
footnote:[Psalm 51:6]
which God requires.
The heart and affections must be cleansed and purified
before we can be acceptable to God;
it was therefore death to me to think of taking up my rest in a formal pretense of holiness,
in which covering I saw (to my grief) an abundance of people had wrapped themselves,
and were sleeping securely and quietly, dreaming of the felicity of paradise,
as if heaven were now their own and they needed not
trouble themselves any more about religion.
I could not entertain so dangerous an opinion as this;
for then I would be tempted to take up my rest along the way,
while still traveling towards the Promised Land.

While I lived in the communion of the national church,
I think I made a little progress in a holy life,
and through God`'s assistance I weakened some of my spiritual enemies.
I thank my God I can truly say, that while I used their prayers,
I did it with zeal and sincerity, in His fear and dread;
but still I ceased not my earnest supplication to Him in
private that He would show me something more excellent;
that I might get a complete victory over all my lusts and passions,
and might perfect righteousness before Him.
For I found a great many sins and weaknesses daily attending me,
and though I made frequent resolutions to forsake those sins,
yet still the temptations were too strong for me;
so that I had often cause to complain with the apostle in the bitterness of my soul,
"`O wretched man that I am!
Who shall deliver me from the body of this death?`"^
footnote:[Romans 7:24]
Who shall set me free and give me strength to triumph over sin, the world,
and the devil?--that in everything I may please my God,
and that there may not be the least thought, word or motion, gesture or action,
but what is exactly agreeable to His most holy will, as if I saw Him standing before me,
and as if I were to be judged by Him for the thought of my heart the next moment!
Oh divine life!
Oh seraphic soul!
Oh that I could always stand here!
For here is no reproach, no sorrow, no repentance;
but at God`'s right hand there is perfect peace and a river of unspeakable joy.
Oh that we might imitate the life of Jesus,
and be thoroughly furnished unto every good word and work!
This was the frequent breathing of my soul to God when I was in the country,
but more especially after I had left my new office as a chaplain,
and took private lodgings in London.
In this retirement (I hope I may say without boasting), I was very devout and religious,
and found great comfort and refreshment in it from the Lord,
who let me see the beauty of holiness.
Indeed, the sweetness that arises from a humbled, mortified life,
was then very pleasant to my taste,
and I rejoiced in it more than in all the delights and pleasures of the world.

And now it pleased God to show me,
that if I would indeed live such a strict and holy life as adorns the gospel,
then I must leave the communion of the Church of England;
but I knew not yet which way to go, nor to which body of men I should join myself,
who were more orthodox and more steady in their lives.
As for the Quakers (so called),
I was so great a stranger to them that I had never read any of their books,
nor do I remember that I ever conversed with any
one man of that society in my whole life.
I think there was one in Foxly while I was a curate there, but I never saw the man,
though I went several times to his house on purpose to talk with him,
and to bring him off from his mad and wild enthusiasm,
as I then ignorantly thought it to be.
As for that way, I knew it was everywhere spoken against;
for he that had a mind to appear more witty and ingenious than the rest,
would choose them for the subject of his profane jests and mockery.
In this way men make sport, and entertain their company,
for a Quaker is but another name for a fool or a madman,
and is scarcely ever mentioned but with scorn and contempt.
As for mockery, I confess I was never any great friend to it; but indeed,
if all was true that was laid to the Quakers`' charge,
I thought they were some of the worst people that ever appeared in the world,
and wondered how they could call themselves Christians,
since I was told they denied the fundamental articles of the holy faith,
for which I ever bore the highest veneration and esteem.
And furthermore, I had always lived at the greatest distance from this people,
and was very zealous in the worship of the Church of England,
and upon all occasions would speak very honorably of it,
and was even content to suffer a few inconveniences upon that account.

While I lived in London, in that private, retired manner I was just now speaking of,
walking very humbly in the sight of God,
and having opportunity to reflect upon my past life,
I had occasion one day to be at a bookseller`'s shop,
and happened to cast my eye upon Robert Barclay`'s works.
Having heard in the country that he was a man of great account amongst the Quakers,
I had a mind to see what their principles were,
and what defense they could make for themselves; for surely, thought I,
these people cannot be so silly and ridiculous, nor maintainers of such horrid opinions,
as the author of [.book-title]#The Snake#^
footnote:[This book, [.book-title]#The Snake in the Grass,#
which came out in the year 1696, was published anonymously.
The author was employed by some of the clergy to render
Friends and their principles odious to the world.
His misrepresentations were disproved, and his crafty artifices made manifest,
by Joseph Wyeth and George Whitehead in a book
entitled, [.book-title]#A Switch for the Snake.#]
and some others would make us believe.
I took Barclay home with me, and I read him through in a week`'s time,
except for a little treatise at the end, which,
finding to be very philosophical, I omitted.
However,
I soon read enough to convince me of my own blindness and ignorance in the things of God.
For upon reading I found a light to break in upon my mind,
which did mightily refresh and comfort me in that poor, low,
and humbled state in which I then was; for indeed I was then,
and had been for a considerable time before, very hungry and thirsty after righteousness,
and therefore received the truth with all readiness of mind.
It was like balm to my soul,
and as showers of rain to the thirsty earth that is parched with heat and drought.
This author laid things down so plainly,
and proved them with such ingenuity and dexterity of learning,
and opened the Scriptures so clearly to me, that without standing to criticize, dispute,
raise argument or objection, or consulting with flesh and blood,
I presently resigned myself to God;
and weeping for joy that I had found so great a treasure,
I many times thanked Him with tears in my eyes for so kind a visitation of His love,
that He was graciously pleased to look towards me when my soul cried out for Him.
So, though before I was in great doubt and trouble of mind,
not knowing which way to turn,
yet now I found the sun breaking out so powerfully upon me that the clouds were scattered.
I was now fully satisfied in my own mind which way I ought to go,
and to what body of people I should join myself.

So I immediately left the communion of the Church of England,
and went to Gracechurch Street Meeting.
After I had read Barclay, I read some other books of that kind,
among which was an excellent piece, though in a small volume,
called [.book-title]#No Cross, No Crown.#^
footnote:[By William Penn]
Thus I continued reading and frequenting meetings for several weeks together,
but did not let any one soul know what I was doing.
The first man I conversed with was George Whitehead;
and this was several weeks after I began to read Barclay, and attend Friends`' meetings.
By him I was introduced into more acquaintance with them; and still the further I went,
the more I liked their plainness, and the decency and simplicity of their conduct.
They do not use the ceremonies and salutations of the Church of England,
but shake hands freely,
and converse together as brothers and sisters that are sprung of the same royal Seed,
and made kings and priests unto God.
Oh the love,
the sweetness and tenderness of affection I have
seen among this people! "`By this,`" says Christ,
"`shall all men know that you are My disciples, if you love one another.`"^
footnote:[John 13:35]
"`Put on therefore,`" says the apostle, "`as the elect of God, holy and beloved,
tender mercies, kindness, humbleness of mind, meekness, longsuffering.`"^
footnote:[Colossians 3:12]

Thus, my dear friend, I have given you an account of my proceedings in this affair.
As to my bodily state, if you desire to know what it is,
I may acquaint you that I have my health as well as ever,
and I bless God I have food and clothing sufficient for me,
so that I lack no outward thing.
Indeed, I have the necessities and conveniences of life,
so let us not burden ourselves with taking care for the vanities and superfluities of it.
Let us possess our vessels in sanctification and honor;
and even as we bring our minds into perfect subjection to the whole will of God,
so let us bring our bodies to the most simple and natural way of living.
Let us be content with the fewest things, never seeking to gratify our lustful appetites,
nor following the customs and humors of men,
but rather seeking how we may so govern our earthly cares
and pleasures that we may bring most glory to God,
most health and peace to our own souls, and do most service to the Truth.
And if this be our aim,
then certainly a very small portion of the things of this world will suffice us.
Seeing we are Christians,
we should therefore earnestly pursue those things which bring us nearest to God.
For whatever is more than a necessity, seems to be a burden to a soul,
which desires to breathe in a pure vessel,
that so it may have a living sense and relish of all blessings,
both of the superior and inferior worlds.

You know, my dear friend, that religion is a very serious thing.
Repentance is a great work,
and one precious immortal soul is of more worth than ten thousand perishing worlds,
with all their pomp and glory.
Therefore let us take courage and be valiant for the truth upon the earth.
Let us not content ourselves with a name and profession of godliness,
but let us come to the life and power of it, never despairing of getting the victory.
We have a little strength from God;
let us be faithful to Him and He will give us more strength,
so that we shall see the enemy of our peace fall before us,
and nothing shall be impossible unto us.
I say, my friend,
let us be faithful to that measure of light and knowledge which God has given us,
to be profited and edified by it in a spiritual life.
And as God sees we are diligent and faithful to work with the strength we have received,
He will more and more enlighten us,
so that we shall see to the end of those forms and
shadows of religion in which we formerly lived.
But if He sees we are about to take up our rest in those shadows,
or that we grow cold and indifferent in the pursuit of holiness,
running out into notions and speculations,
and have more a mind to dispute and to make a show of learning
and subtlety than to lead a holy and devout life,
then it is just for God to leave us in a carnal and polluted state.
Thus we will continue only in the outward court,
where we may please ourselves with beholding the beauty and ornaments of a worldly sanctuary,
and never witness the veil being taken away,
and being brought by the blood of Jesus into the holiest of all,
where alone there is true peace with God, and rest to the weary soul.
I could say much upon this subject, if time or leisure would give leave.

As for a particular answer to your letter, I have not time now to give it,
but desire for the present to let this general answer suffice.
And if you will consider things in their pure nature,
and not allow the prejudice of education to sway you,
but in fear and humility will search out the truth for yourself,
you will find that there is need for no other answer
to your letter than what I have already given.
For by waiting upon God, and diligently seeking Him,
you will find an answer to it in your own bosom; and this will be much more full, clear,
and satisfactory than I, or any other man living, can pretend to give you.
For truly I desire that you,
together with all the sincere-hearted in the Church of England,
may come to witness the almighty power of God to save and redeem them from every yoke;
and that they may clearly "`see to the end of those things which are abolished,`"^
footnote:[2 Corinthians 3:13]
and come to the enjoyment of spiritual and heavenly things themselves.
Indeed, this is the daily prayer and deep travail of my soul, God knows.

Until I can be more particular, if you please you may communicate this to the others,
and let them know that I am well, and thank them for their kind letters.
Let us remember to pray for one another with all fervency,
that we may stand perfect in the whole will of God.
Amen, says my soul.

[.signed-section-closing]
I am your most affectionate friend and servant in Jesus,

[.signed-section-signature]
Samuel Crisp.

[.centered]
==== Letter II.

[.salutation]
My dear friend,

I lately received a kind and brotherly letter from you,
for which I return you many thanks.
I am now in the communion of the people called Quakers,
and I have cause to bless God for this happy change of my life.
I am, through mercy, brought off from the shadow of religion,
and am pressing forward to get acquaintance with the quickening power, life,
and virtue of it, that I may be a Christian indeed,
and not in the name and profession only.
For a great while I had talked and discoursed of holiness,
but did not understand what it was to walk with God, to live and dwell in Him.
Perhaps, indeed, some may think I made a fair show of piety when I was with you; but,
alas!--I was deeply sensible of my own faults and miscarriages, and I resolved,
through God`'s assistance,
to inquire after something more noble and excellent than I had discovered in that state.
And blessed be His name forever, God has answered the cry of my soul,
and let me see a people that are hated and despised by the world, but are dear to Him;
for He has revealed to them the mysteries of the kingdom.
He has carried them upon eagles`' wings, and cherished them as the apple of His eye.

As for me, I have thus far been but in the outward court,
and far short of that truth and righteousness that
is taught and practiced among this people;
for they are come within the holiest of all.
Indeed, they are come into a near communion with God,
to behold the cherubim of glory that cover the mercy seat,
and to be fed with the true manna.
These are mysteries that are revealed unto the meek and lowly; but the haughty, insolent,
and profane cannot come near them, nor taste of the sweetness or comfort of them.
The formal, traditional sort of people of the world may talk of these things,
according as they have heard them from others,
and in their sober moments may have some faint glimmerings that way;
but to come to the real and inward enjoyment of them, they can no more claim,
than to work the greatest impossibilities.
Indeed, all their wit, subtlety,
and learning cannot reach high enough to handle the Word of life;
for this is known only to those who are content to forsake all,
and become fools for Christ.
Yes, only these are in a good frame to receive and cooperate
with the influences of the Holy Spirit,
having seen the emptiness and vanity of all those
things that are so much admired by the world.
The schools and universities, learned doctors and great rabbis, have not profited me,
for they have departed from the Spirit of God,
and gone out into their own notions and speculations,
thinking thereby to search out God and comprehend the truth.
Alas!--the mysteries of the kingdom are far out of their reach in their carnal minds;
they weary themselves in vain, for the vulture`'s eye cannot pierce into these secrets.
All the great critics, scholars, and philosophers of the world are fools in these things.
They are wearying themselves to find the deep things of our God,
studying and racking their brains,
tossing and tumbling to and fro like a wild bull in a net that
knows not how to disentangle himself--the more he struggles,
the weaker he grows and the faster he is bound.
So too, the more these vain talkers read, the more they write,
the more they cavil and dispute, the further they are from God,
and the more they manifest their hatred and enmity to the Spirit of Christ,
and to the simplicity of the gospel.

I have been, for a long time, weary of the folly and impertinency of these men,
and chiefly the celebrated "`fathers of the church,`" as they call them.
The councils and synods of old are now of very little account with me.
I am not ashamed to sit under the teachings of women and mechanics,
howsoever they may seem in the eye of the world; for truly,
these now teach me more Christianity, and instruct me more perfectly in a divine life,
than all the studied,
elaborate sermons and discourses that ever I heard at the universities or since.
Their words are with power; indeed, they are mightily assisted with the Spirit of God,
and speak with majesty and authority, and there is a native beauty, clearness,
and solidity of expression that shines through their discourses
which is sufficient to answer that groundless slander,
namely, that the Quakers`' preaching is nonsense, and nobody can understand them.
This I have often heard refuted by many living testimonies,
so that I do rather think them the best minds,
and the most ingenious people in the world;
for they employ their abilities and learning in the fear of God,
to His glory and service, and to promote the true interest of mankind.

As for the common little jests, witty comments, and vain showmanship of the age,
which I know the world has esteem for (and nothing
will please but what abounds with such fooleries);
I say, if the Quakers are deficient in any of these, it is not for lack of abilities,
or because they have less wit than other men,
but because they have more prudence and wisdom to govern it.
That is the reason why they avoid such childish vanities,
which are so freely used and indulged in by others, to the great dishonor of God,
and the Christian religion.
Therefore, because they do not seek to please a loose and shameless age,
and make people laugh and be merry, nor to entertain that carnal,
airy mind with pleasant stories, fine notions, and witty expressions of natural things,
from here it is that they have been shamefully misrepresented
by the world as the most ignorant,
blind, and foolish people that ever made any profession of religion.

Yet this is the people to whom I have now joined myself in a sincere love to truth;
and God knows,
I glory more in this fellowship and acquaintance with these lambs of Christ,
than if I were related to the greatest kings, lords, and potentates upon the earth.
Oftentimes has my spirit been refreshed with theirs
when we have met together to wait upon God;
and my soul still longs and pants more and more to be filled with these divine comforts.
He is ready always to pour down blessings upon us,
if we would but qualify ourselves for the reception of them;
if we would put away vain thoughts, which cloud and darken the mind,
and so hinder the favorable influences and illuminations of heaven.
And since it has pleased God to visit me of late,
and to make known to me excellent things in righteousness,
He alone is to have the praise and glory of all;
and I now freely resign myself to the guidance of the blessed Spirit.

Now let the truth prosper!
Let it run and be glorified in the earth!
Let it shine out in its full luster, to the terror and confusion of all its enemies,
and to the reviving of the souls of the hungry and thirsty, who are ready to faint,
waiting for and expecting the consolation of Israel,
until the time of refreshment comes from the presence of the Lord.
Truly, He will open a fountain for Judah and Jerusalem,
so that rivers shall run in dry places, and there He will speak peace to His people.
And after they have sat silent a little while in the dust,
suffering patiently the chastening rod of His love to pass over them,
He shall then comfort the daughter of Zion, and say, "`Arise, you afflicted,
and weep and mourn no more, but put on your beautiful garments, O Jerusalem!
Raise your head, uncover your face, and gird up your loins with strength;
see the day break, and the morning spread itself upon the mountains;
for now the sorrowful nights of affliction have passed over,
the clouds are scattered and gone, the sun has arisen in its brightness,
and now joy and peace shall be multiplied.
In a little wrath I hid My face from you for a moment,
but with everlasting kindness will I have mercy on you, says the Lord your Redeemer.`"

Oh then, let us wait, in humility of soul and tenderness of heart before the Lord,
that we may witness this great change and salvation wrought in us and for us,
so that the Scripture may no more be a sealed book to us,
but that we may _feel_ the precious truth therein recorded to be fulfilled in ourselves.
Then we shall never be weary of praying and reading the Holy Scriptures.
We shall never be afraid or unwilling to come into God`'s presence; for His love,
and the sweetness of His ointment,
will draw and allure us to dwell always under His canopy,
that we may feel life and power to flow from Him,
who is the ocean that supplies all the needs of the children of men.
And how shall we come to taste that heavenly banquet which he has prepared for us,
that we may eat and drink at His table, and that our souls may delight in fatness--I say,
how shall we attain to this, but by a strict and mortified life?
Certainly the more we retire from worldly joys,
and empty ourselves of earthly comforts and false delights,
the fitter we shall be to receive those that are spiritual and heavenly;
and not only to receive and rejoice in them for a time,
but to live and dwell in them forever.
For this is the life of Jesus, and here the kingdom of God reigns in the heart and soul,
by which it is changed from glory to glory, even as by the Spirit of the Lord.

And now I would ask all the wise and prudent, all the rich,
all the noble and learned men of the world, what they think of these things?
Whether such things can be learned in their courts and palaces?
Or whether any of the great scholars and universities in Christendom
can furnish us with such a system of divinity as this?
No; they hate and despise it; and instead of a sober answer to my inquiry,
they return scoffs and contempt.
"`This is babbling,`" they say,--
"`an idle dream, and forged delusion of his own brain;`"
and many more opprobrious names they have given to such inquiries as these.
Sometimes perhaps they will soften their expression with a hypocritical show,
pretending to pity me,
and calling it an unhappy effect of melancholy and too much withdrawal from the world.
This some think to be too much condescension,
and that I ought to be grateful to them for giving it so mild a character;
for at other times they deal more sharply, and confidently say that it is madness,
delusion, witchcraft, and diabolical fanaticism.
But I am content to lie under all these odious imputations from the world,
knowing very well, that better men than I have suffered the same things before me,
and do at this present time.
As for my enemies, I can truly say, I thank God I can pity them and pray for them;
they do not hurt me, but themselves.

And now my dear friend, before I conclude,
allow me a little to speak of your present circumstances; for as God knows,
my heart yearns towards you in the tender love of Jesus.
I suppose you are now where I left you, with the lord Richardson (so called),
in the capacity of a chaplain--an office which I have had a little experience of myself,
since I last saw you, but was quickly so weary of that servile yoke,
and so unworthy of that holy function I bore,
that in ten days`' time I relinquished my new preferment,
and left it more free than ever I undertook it.
What peace or satisfaction you can have in such kind of employment, I know not;
for my part I could find none.
My soul was grieved and burdened every day with seeing and hearing their evil deeds,
beholding their vanities and excesses.
Indeed, this was as a sword to my soul and spirit, it wounded me very deep;
and I do solemnly profess,
I had rather beg my bread from door to door than to live in the like bondage again,
where I must be obliged to perform such ceremonies and formalities,
to flatter men in their sins, to cry, "`peace, peace;`"^
footnote:[Jeremiah 6:14-8:11; Ezekiel 13:10,16]
and to "`sew pillows under the armholes`"^
footnote:[Ezekiel 13:18]
of delicate people, who can never bear the least check or frown,
but rather expect the mercenary priest should always laugh or smile in their faces,
even when he sees plainly they are going to hell and destruction.
And yet I must tell you that the family I was in
was looked upon as one of the most sober and consistent,
as far the world goes now.
And I must also say, I did not leave them for any drinking, gaming,
or swearing that I perceived among them; for as to all these filthy,
scandalous practices, as far as I could see, they were blameless.
Yet I saw their hearts were not right,
for they were lovers of pleasure more than lovers of God; and you know that he or they,
let them be great or small, if they live in pleasures,
they grow fat and careless towards Christ; such persons "`are dead while they live.`"^
footnote:[1 Timothy 5:6]
I say, whatever their faith, or principles, or professions may be,
yet in true religion they are dead.

I shall say no more, but hasten to a conclusion.
If you desire a particular account of my convincement,
you may see it in a letter I wrote lately to Richard Lake, junior,
wherein I gave him a fair and true relation of my proceedings in that matter,
what steps I took,
and how God did graciously assist me when He had raised
in me sincere desires and inquiries after truth and holiness.
Dear friend, I have no more at present,
but to let you know that I do most heartily pray for you,
that you may consider things without prejudice,
and not allow any of the temptations and allurements
of the world to draw your mind from God,
and to hinder you in your pursuit of holiness.
He that loves father or mother, brother or sister,
or any of the endearments of this world, more than Christ, is not worthy of Him.
But if you will come into communion with Christ,
and follow the guidance of His light and spirit,
oh what a blessed and happy rest you shall find for your soul!
Oh what rivers of living waters will spring up in you!--of which you may drink freely,
and praise God for all His mercies and benefits.
That you may indeed come to such spiritual enjoyments and refreshments as these,
is the sincere desire of

[.signed-section-closing]
Your loving and affectionate friend,

[.signed-section-signature]
Samuel Crisp.

[.centered]
==== Letter III.

[.signed-section-context-open]
Leeds, Sixth month 7th, 1702.

[.salutation]
Loving friend,

This may acquaint you that last fourth-day was a
week since I got well to my journey`'s end.
But though my body now rests as to the outward,
yet I still feel a necessity to continue my inward,
spiritual travel towards the new Jerusalem, the heavenly Canaan,
where my soul may be satiated with everlasting and unchangeable felicity.
I must still keep on my watch,
that the enemy of my soul may not at any time take an advantage against me.
I must still stand upon my guard, go on in the Lamb`'s warfare,
and diligently pursue such things as may make my calling and election sure.
And this, I think, is the state of every Christian, so long as he sojourns in this world.
Perfect and complete rest and peace are only to be
expected when we have laid aside these mortal, frail bodies,
and shall enter those mansions of glory that Christ our Head has prepared for us.
But if we would reign with Him in another world, we must suffer with Him in this.
If we would wear the crown, we must first bear the cross.
If we would be conquerors, we must fight.
If we would win the prize, we must not be lazy and indifferent,
but exert all our strength in the Christian race.
In short, if we would be perfect, we must sell all, part with all our lovers,
and sacrifice all the nearest and dearest enjoyments that we have in this world.
This is self-denial; this is mortification indeed; and this is that repentance unto life,
never to be regretted.
My love to your uncle and Friends.

[.signed-section-closing]
I am your loving and affectionate friend,

[.signed-section-signature]
Samuel Crisp.

=== Extracts from Samuel Crisp`'s Vindication of the People Called Quakers

[.offset]
+++[+++The first of the two following pieces is extracted
from the Preface to Samuel Crisp`'s [.book-title]#Vindication,#
and the second is taken from the treatise itself.
It is believed that the weighty counsel, sound doctrine,
and instructive remarks which these extracts contain,
will commend themselves to the cordial acceptance of any serious reader.]

==== A Plea for the Truth, and an Earnest Exhortation to be Found Walking Therein.

[quote.scripture, , Jer. 6:16]
____
Stand in the ways and see, and ask for the old paths, where is the good way,
and walk therein, and you shall find rest for your souls.
____

[.salutation]
Reader,

I desire you would be serious and unbiased in the
reading of what I here present to your view,
so you may reap benefit and advantage by it to your soul.
The noise and clamor against the Quakers has, of late years,
been carried on and promoted with great diligence by their adversaries;
insomuch that few, I think, who converse with the world, can be ignorant of it.
This gave me occasion to inquire into their principles;
and in order that I might not take things upon trust,
or believe the report of others concerning them, I was willing to see for myself,
to read and consult their own authors.
To this I applied myself with great seriousness;
desiring of the Lord (in great humility and submission of soul) that He
would open my understanding in the great things of His law,
and that if the truth was among the Quakers, I might,
without consulting with flesh and blood, join myself to that people,
however slighted and despised I might be by the world for so doing.
It was peace with God I wanted; and in comparison of that,
I looked upon all other things as dross and dung.

I was brought up in the national way of worship,
and had been strict and punctual in the rites and
ceremonies of the Church of England beyond many;
yet I found all that would not do, for the Seed was oppressed,
and death still reigned under all those forms and outward appearances of godliness.
It was an easy matter to talk, and to do the round of my devotions,
but I lacked strength and power to overcome my sins and corruptions.
There was a cry raised in my soul after righteousness and truth,
and I found that all my outward observances could not give it,
for the kingdom of God is within men, though I was seeking for it abroad,
doting upon shadows.
Thus I was diverted from the pursuit of the knowledge of the truth, as it is in Jesus.
I lived in darkness and ignorance of the true and saving knowledge of God,
notwithstanding my lofty pretensions.
But it has pleased God to rend the veil,
and in a good measure to disperse the clouds and scatter the mists and fogs;
blessed be His name.

Know, reader, that there is a people in this age, who have paid something for religion;
and they will not be put off with shams and pretenses,
nor allured by the wiles of the enemy.
They are not easily to be misled in the important
things that concern their everlasting peace.
They cannot bow to images,
nor satisfy themselves with the husks and formalities of religion,
but they labor to come into the life of holiness and the real practice of virtue,
and neither smiles nor frowns can prevail with them to forsake the truth.
These the devil envies, and to render them odious, he paints them in black colors.
To be sure, in his account, they are fools and madmen, fanatics, schismatics, heretics,
a dangerous sort of people.
"`Sirs,`" they say, "`look to yourselves, and as you love your souls,
beware of the infection of Quakerism.`"
This is the common language, whenever a people do not please the devil;
but if they are passive and open to his insinuations,
if they can rest in an outward form, and dwell upon words and notions,
then he reigns in peace; his kingdom is quiet, and no hard names are needed.

Well, reader, what I said before, I repeat now: it concerns you to be serious,
and to weigh things with a clear and unbiased mind.
If you will serve God, you must take courage and break loose from the world.
If you will come to Christ,
you shall find true riches and a fountain of inexpressible joy.
If you die with Christ, you shall live; if you suffer with Him in this vain,
transitory world, you shall reign with Him in glory forever.
Look not at your own weakness, but look unto God, whose grace is sufficient for you;
His strength is magnified in our weakness.
Therefore, let not the cross discourage you, but take it up,
and in meekness and patience bear it after Jesus,
who for the joy that was set before Him endured the cross, despising the shame,
and has set down at the right hand of the throne of the majesty in the heavens.
Strip yourself from created things; wean your affections from the world;
strengthen your hands in God; cleave steadfastly unto Him.
Make Him your friend, and then you need not care who is your enemy;
all the rage of men and devils can never hurt you.
Hearken unto God and obey His voice;
mind the teachings of His Holy Spirit and give yourself up entirely to its guidance,
for its ways are ways of pleasantness and all its paths are peace.
This is that Comforter which is given to lead us into all truth,
and blessed are all those that are taught and led by it.
These are enabled to see their way; it is made plain,
and shines more and more unto the perfect day.
Do not entrust yourself to uncertainties, nor put off your repentance;
delay not the time of returning to God,
for how do you know you shall live an hour longer?
Are all your accounts fair and clear?
Are you ready to depart if God should call you before tomorrow morning?

Reader, once more I say: it concerns you to be serious;
for the day of God hastens wherein all false coverings shall be torn off.
Fear shall take hold of the hypocrites as sorrow upon a woman in travail,
and they shall not escape.
A name and profession of Christianity without the life and
power of it will then be of very little advantage.
Indeed, it will be a terrible day, and who shall be able to stand in it?
Certainly none of the hypocrites, shufflers, vain talkers, and disputers of this world;
none of the empty notionists, pretenders, and men-pleasers; no,
these will all be swept away as chaff before the wind.
"`For behold the Day comes that shall burn as an oven; and all the proud, yes,
and all that do wickedly, shall be stubble.
The Day that comes shall burn them up, says the Lord of Hosts,
and it shall leave them neither root nor branch,`" Mal. 4:1. Therefore,
now is the accepted time, prize it.
Now is the day of salvation.

Know therefore, reader, that by the grace of God you are capable of great attainments.
True faith will remove mountains,
and by it you may escape the pollutions of the world
and come clean out of Babylon and Egypt,
and all such things as would restrain or hinder you in your Christian race.
Why then should we trifle away our precious minutes?
Why should we die short of true happiness?
Let the time past suffice for us to have wrought the will of the Gentiles,
serving various lusts and pleasures and walking in the vanity of our minds.
God has borne long with us; His mercy and lovingkindness has been great.
Let us provoke Him no longer,
but immediately return to Him and humble our souls before Him.
This is the labour and travail of my soul, God knows,
desiring that all men might be saved and come to
the knowledge of the truth as it is in Jesus.
Oh that all would taste and see how gracious He is!
If they would but wait upon Him in silence,
with their minds retired from the world and fixed upon Him,
they would come to see wonderful things in righteousness.
Yes, the mysteries of God`'s kingdom would be opened and revealed to them;
things which were kept secret from the foundation of the world.
Such would find true peace and rest to their souls.
They would find strength administered according to their various needs,
and grace to help in time of need; yes,
they would go from strength to strength and grow in grace daily,
as the apostle said in Ephesians 4:13; "`till we all come in the unity of the faith,
and of the knowledge of the Son of God unto a perfect man,
unto the measure of the stature of the fulness of Christ.`"
That we may all come to know, witness and experience this in ourselves,
is the earnest supplication and prayer of your hearty well-wisher and sincere friend,

[.signed-section-signature]
Samuel Crisp.

==== On Divine Worship, Gospel Ministry, and the True Church.

[quote.scripture, , John 4:24]
____
God is a Spirit; and they that worship Him,
must worship Him in spirit and in truth.
____

Our Christian belief,
is that every man ought to wait upon God in the measure of His own good Spirit;
and that he is to follow its motions, observe its counsels,
and make it the great rule and guide of his life.
It is as men wait in this Spirit, and are led and governed by it,
that so (and not otherwise) they are accepted and approved in the sight of God.
For this, and this only, can work all acceptable works in us and for us.
"`Walk in the Spirit, and you shall not fulfill the lusts of the flesh.`" Gal. 5:16.
"`For as many as are led by the Spirit of God, they are the sons of God.`" Rom. 8:14.
In the performance of all religious worship,
we say there is special need that men should wait upon God in the gift of His own Spirit,
to feel the guidance and assistance of it;
for this is the salt of the sacrifice that gives savor and life to every duty.
It is this Spirit that must make known our needs to us,
and instruct us how to apply ourselves to God for suitable relief.
The apostle to the Gentiles has this excellent saying: Rom. 8:26-27,
"`Likewise the Spirit also helps in our weaknesses;--and He that searches the hearts,
knows what is the mind of the Spirit is,
because He makes intercession for the saints according to the will of God.`"
God is to be worshipped in spirit and in truth, and so we wait upon Him in silence,
that we may be enabled to perform this worship and service,
believing that His Spirit will help and teach us to pray
better than all directories and common-prayer books.
Shall we for this be ridiculed?
And because we are tender of the righteous Seed of light and life in ourselves and others,
observing what the apostle enjoins--not to quench the Spirit nor despise
prophesying--must we therefore be called fanatics and enthusiasts?

It is not men`'s running through their prayers by heart, or reading them out of a book,
or undertaking to pray or preach by the strength of their own reason and natural faculties,
that finds acceptance with God.
None of these can be said to be that spiritual worship and
service which God calls for in the days of the Gospel,
now that He has sent forth the Spirit of His Son into our hearts,
whereby we cry Abba Father.
Not now, I say, when He has poured forth His Spirit upon sons and daughters,
so that they can and must prophesy; not now,
when God has so clearly revealed Himself to the world,
and told us expressly by His Son that He is a Spirit,
and that the true worshippers shall worship Him in spirit and in truth,
and that He seeks such to worship Him.
These are _Gospel_ days.
This is the last and most glorious dispensation that shall ever be in the world;
and now God calls for a more than ordinary strictness and purity of life.
"`The times of ignorance,`" it is said,
"`God overlooked; but now He commands all men everywhere to repent;`"^
footnote:[Acts 17:30]
to leave off their dead forms, their empty ceremonies and hypocritical will-worship,
a worship which they can go about in their own time,
beginning and finishing it when they please.
Here many are making a profession of religion and godliness outwardly,
going on in a round of bodily ceremonies and pretended devotions,
from one year to another, and yet are destitute of the inward,
experiential knowledge of Jesus Christ.

But blessed be God forever,
that in this generation He has made bare His arm in a wonderful manner,
and brought a remnant near to Himself.
These have seen to the end of types and shadows, and have come to Christ,
the life and substance,
and to the one spiritual baptism that purges the
conscience from dead works to serve the living God.
And they have come to the true supper,
and inward communion of the body and blood of Christ, where they feed daily at His table,
and eat of that bread that came down from heaven
which nourishes the soul unto eternal life.
These have been brought off from all the world`'s carnal and literal teachers,
and have come to the ministration of the Spirit,
and the teachings of Christ Jesus who is their Prophet, Priest, and King,
the only true Shepherd and Bishop of their souls.
These have come to a true silence, and a ceasing from all their own words;
they wait for the arising of that Divine Power and Life which shall render
their service acceptable to God and useful and beneficial to men.
They preach and pray as the Spirit helps them.
They observe Christ`'s rule and precept, which is, to "`watch and pray;`"^
footnote:[Matthew 26:41; Mark 13:14,33:38; Luke 21:36]
which plainly shows that before men pray, they should watch; that is,
retire in their minds and wait upon God, that they may "`serve Him acceptably,
with reverence and godly fear; for (as the apostle says) our God is a consuming fire.`"

Those who rush hastily into His presence, without due preparation and watchfulness,
"`offer the sacrifice of fools;`"^
footnote:[Ecclesiastes 5:1]
they "`do not come up with acceptance on God`'s altar.`"^
footnote:[Isaiah 60:7]
It is said of Nadab and Abihu, that "`they offered strange fire before the Lord,
which He had not commanded them.
So fire went out from the Lord and devoured them, and they died before the Lord.`"^
footnote:[Leviticus 10:1-2]
Let the ungodly and uncircumcised priests and people of the world--who on all
occasions are so full of their prayers and devotions--consider this!
I am confident they would be ashamed to appear before some of their superiors
in the posture wherein they many times appear before God.
But, as I said before, they who know God rightly,
have learned to wait upon Him in the silence of all flesh.
"`Without me,`" says Christ, "`you can do nothing.`"^
footnote:[John 15:5]
Being deeply aware of this, they have learned to bow and humble themselves before God;
not daring to open their mouths or speak a word,
except as God is pleased to make known to them the mysteries of His kingdom,
to prepare a sacrifice for Himself,
and to touch their lips with a live coal from the altar.
When the well springs up, _then_ they can sing unto it (Num. 21:17).
When God opens, none can shut; and when He shuts none can open.
Therefore these wait, as the apostles did at Jerusalem, to receive power from on high.
And when God bids them speak, they must speak;
they may neither add to that which is given them, nor diminish from it.
They must not quench the Spirit, nor despise prophesying (1 Thess. 5:19-20).

This is our Christian belief with respect to the
worship of God and the solemn offices of religion,
such as praying and preaching.
And by the passages cited,
it may appear to every impartial eye that these are no "`new lights`"
or "`upstart notions,`" but are agreeable to Holy Scriptures,
and to the practice of the primitive Christians; to whose blessed example,
and holy and pious lives, we desire in all things to conform ourselves.

The church of the living God is the pillar and ground of Truth.
It is built upon the foundation of the apostles and prophets,
Jesus Christ Himself being the chief cornerstone.
The church consists of living stones, that are built up a spiritual house,
a holy priesthood,
to offer up spiritual sacrifices acceptable to God through Jesus Christ.
These are a chosen generation, a royal priesthood, a holy nation, a peculiar people,
who in life and conduct show forth the praises of Him who
has called them out of darkness into His marvelous light.
This is a glorious church, not having spot or wrinkle or any such thing,
but is holy and without blemish.
This is the true church and true religion,
which we desire all people would seriously consider and diligently press after.

[.asterism]
'''

[.emphasized]
This short collection of the letters and writings of Samuel
Crisp show him to have been a young man of uncommon sincerity,
humility, and genuine piety.
It is unclear whether he was ever called to publicly minister in the Society of Friends,
but he is known to have been in the company of that esteemed minister, Samuel Bownas,
during his gospel services in the west of England, in the year 1702.
Of him Bownas writes in his journal,
"`I had in company a young man that had been bred at college,
his name was Samuel Crisp--a pleasing, meek-spirited youth, and rightly convinced.
He was a sweet companion, having received the knowledge of the truth the right way.`"
Having clearly begun to build on the one sure Foundation,
it is likely that many had expectations that Samuel Crisp
would become a serviceable member of the church in his day.
But any hopes of this kind were only realized to a very limited extent,
inasmuch as it pleased the All-wise Disposer of events to cut short his life.
He died of the small-pox, at Stepney, east of London, the 7th of fourth month, 1704,
in the 34th year of his age.
