[quote.epigraph, , 1 Thess. 5:21]
____
Prove all things; hold fast that which is good.
____

== Life and Letters of Samuel Crisp

=== Memoir of Samuel Crisp.

Samuel Crisp, previous to his joining the Society of Friends, resided in Norfolk.
He was educated at college,
and took the order of deacon in the church of England (so called);
after which he officiated as a parish curate, also for a very short time,
as chaplain in a private family.

In the year 1700, being then resident in London, and about thirty years of age,
he was convinced of the truth, as professed by Friends,
in the manner described in his first letter.
Soon afterwards he was engaged as an assistant to Richard Scoryer,
a Friend who kept a large boarding-school at Wandsworth.
In this situation he did not remain long,
and subsequently opened a school on his own account, at Stepney, near London.

His adoption of the views and principles of Friends, drew on him, not only remonstrances,
but also contumely and slander.
On his first showing an inclination to unite with them, an acquaintance of his,
a priest of the church of England, who was anxious to prevent his so doing,
proposed to introduce him to a person, who, he said,
was so well acquainted with their writings,
that he did not doubt of his receiving satisfaction.
Samuel Crisp, desirous of being rightly informed,
and of exercising due consideration before taking so important a step,
accepted the offer.
He was accordingly taken to the proposed instructor,
who proved to be no other than Charles Lesly,
the writer of that notorious work called [.book-title]#The Snake in the Grass.#^
footnote:[This book, which came out in the year 1696, was published anonymously:
the author, who was a "`non-juring parson,`" was employed by some of the clergy,
in this way to render Friends and their principles odious to the world.
His misrepresentations were disproved, and his crafty imposture manifested,
by Joseph Wyeth and George Whitehead, in a book,
entitled, [.book-title]#A Switch for the Snake.#]
It seems this person succeeded in putting him to a stand for a very short time;
but he soon discovered the fallacy of his arguments and insinuations,
and forthwith joined in communion with the people to whom he had felt attracted;
and this, as he feelingly acknowledged, from
"`a sincere love of the Truth, and pure regard to his own soul.`"
Soon after this interview, two Letters were addressed to him by Lesly,
to the first of which he sent a Reply,
accompanied with a copy of a Paper written by Richard Scoryer,
proving the falsehood of an assertion contained in
[.book-title]#The Snake,# that the Bible was never read in his school.
This correspondence,
(with a Preface, to which the title belongs rather than to the Letters,)
was published in the following year (1701),
under the title of [.book-title]#The present State of Quakerism in England.
Upon occasion of the Relapse of Samuel Crisp to Quakerism.#

These letters to Samuel Crisp, are as might be expected,
of much the same character with the writer`'s former scurrilous work,
both as regards the manner in which the doctrines of Friends are vilified,
and Samuel Crisp`'s conduct relative to his convincement, is maligned.

Some time afterwards, Samuel Crisp published a refutation in detail,
of the charges preferred against him by this opponent, as fickleness, enthusiasm, etc.,
with an able defence of some of the principles of Friends,
in a Treatise of three-and-a-half sheets, 12mo,
entitled [.book-title]#A Libeller exposed; being a Vindication of the people called Quakers,
against the malicious attempts and foul aspersions of a book entitled,
'`The Present State of Quakerism in England.`'#

This little work, however the circumstance which called it forth is to be repudiated,
furnishes interesting information,
and a clear exposition of some important points of doctrine; various extracts from it,
are therefore given in the present compilation.
From this source we obtain the following particulars and remarks,
relative to Samuel Crisp`'s withdrawing from the communion of the established church,
and the stations he occupied therein.

[.embedded-content-document]
--

As to my leaving the church of England,
God is my witness I did it in pure obedience to the convictions of my own mind;
and the peace which I have often felt returned into my bosom, is more than I can express:
I have had a great and abundant reward from the Lord for what I have done in this matter.

I desire to fear God,
and am heartily sorry that I have spent so much time in
the vanities and impertinencies of this sinful world;
taking things upon trust, swayed by temporal interests,
and following the prejudices of my education.
It is true I was in the order only of deacon,
and I bless God that I went no farther in such orders.
Then I pretended to preach, and could make shift to patch together an hour`'s discourse,
with something that I got from others, and something that I had read from the Bible,
filling up the vacancy with the dark conceivings of my own brain--and this was my gospel.
I could talk much of Christ, and heaven and hell, and extolled the Scriptures highly,
which were nevertheless a sealed book to me; for though I read them often,
both in public and private, yet my mind being outward,
and not waiting in silence upon that Holy Spirit that gave them forth,
I knew not the Scriptures nor the power of God:
so then the power of death and darkness ruled in me.
I had cure of souls, (as they call it,) but was a physician of no value, I knew, indeed,
that I had served my time at the university, as apprentices do to a trade;
and that I had passed the examination and the ceremony
of ordination--and I thought this would do;
but as for any immediate call or appointment of God, to the work of the ministry,
I knew nothing of it.

I had the care of two parishes committed to me, by the bishop of the diocese,
but had never any call from God to go and preach to that people.
So I was like those prophets Jeremiah speaks of, chap, xxiii.
21, who ran before they were sent, and therefore they could not profit the people at all.
I was a superstitious bigot--a poor dark creature--a
hireling--a blind leader of the blind.
I expected thirty pounds a year for preaching--that was my wages;
and if any should question my commission, I knew I had a little piece of paper to show,
which I called my orders, if that would satisfy them;
so brutish was I in my understanding.
And yet God did not leave himself without a witness;
for in the midst of all this darkness and ignorance, I can truly say,
there was a measure of sincerity in me; and good desires,
and earnest cries and breathings were oftentimes raised in me,
that I might once know the Lord and serve him, and see his glory,
and witness peace and joy, and health and rest, and salvation to my soul,
before I went off the stage of this world;
that so I might live with him in that world which never shall have an end,
when time here shall be no more.
And God was not unmindful of the travail of his own seed in that day;
for blessed be his name, he heard the groanings of it under a great deal of rubbish,
and he revealed his Son in me,
at the brightness of whose appearance the clouds are scattered and the shadows flee away.
May the sense of his goodness and tender mercy never depart from me,
so long as I have an hour to live, or a minute to breathe in this world.
Even to the same God that had compassion on Israel of old,
when they sojourned in a strange land,
where the Egyptians and Pharaoh oppressed them with much
cruel and hard bondage--to that God I ascribe my deliverance,
who alone is worthy to be praised,
magnified and adored by all who make mention of his name.
He remembered us when we were in trouble, and anguish, and deep affliction;
being scattered upon the dark and barren mountains, as sheep without a shepherd;
wandering from mountain to hill,
from one form and empty profession of religion to another; even there did he find us,
and his eye pitied us, and he said to the dry bones, Live;
for his mercy endures forever.`"

--

His office as chaplain, (in which it seems he continued but ten days),
proved particularly irksome and unsatisfactory;
and it is probable that the circumstances connected with it, strengthened,
in no small degree,
his desire to be disengaged from the forms and ceremonies in which he had been educated.
On alluding to his situation in that capacity, he states,
that he has had to wait three or four hours at a time,
to know when the family would go to prayers;
and that his task was not finished when the prayers were ended,
as he was expected to wait, to be ready when called for,
in an adjoining room where servants and others were often passing, and company coming in;
and that he was sometimes thus kept in waiting, from morning till night.
As he had occasion for some employment by which to procure a livelihood,
such inconveniences as these would probably have
been borne till an appointment less wearisome presented,
could he have continued here, and at the same time have enjoyed peace of mind:
but he writes:

[.embedded-content-document]
--

I left my chaplain`'s place purely upon a foot of conscience; the lustre of mammon^
footnote:[Samuel Crisp in his Reply to Lesly`'s first Letter, had stated,
that his "`way being cleared up and the Truth shining out again in great lustre,
he found a necessity to return into the strait and narrow path,
where he hoped to continue,`" etc.
His opponent tauntingly alludes to this expression by saying,
"`At last we heard you were established as usher to the grand Quaker-school at Wandsworth,
and you told us your lustre was come!
I will not be so uncharitable as to suppose it was the lustre of mammon,
for the sake of such a provision;
you being destitute before.`"
{footnote-paragraph-split}
It is pleasant to turn from such a prejudiced,
ill-conditioned judge, to one whose testimony savour of truth and love.
Samuel Bownas,
in an account of a journey which he took in the early part of the year 1702,
from London to the west of England, on religious service, says,
he "`had in company a young man that had been bred at college,
his name was Samuel Crisp--a pretty, meek-spirited youth,
and rightly convinced:`" and a short time afterwards,
when engaged in like manner in Hertfordshire, he speaks of him as
"`a sweet companion, having received the knowledge of the Truth the right way.`"--
See [.book-title]#Life of Samuel Bownas.#]
could not keep me there;
and this was some months before I came among the people called Quakers,
or had the least thoughts that way.
I lived some time privately in London, inquiring after the best things.
There was then a great noise about the Quakers,
and George Keith (who was just then ordained deacon) was the talk of the town.
So meeting one day with Robert Barclay`'s works, in a bookseller`'s shop,
and understanding that he was a Quaker, and an eminent writer among them,
I had a great desire to read them; which I did in the fear of God,
and with a humble mind;
and thereby was so fully convinced of the truth of the Quakers`' principles,
(notwithstanding the clamour of the world against them), that from that day to this,
I have never once communicated in the church of England.
And though I was then destitute of any outward business,
yet I did not doubt but the Lord would some way provide
me a competent subsistence in this world,
which was all I desired--and this accordingly came to pass;
for within a few weeks I was recommended to Wandsworth school,
Richard Scoryer being then in need of an usher.
But, just upon my convincement, two things offered to draw me back again into the world:
one was, to read prayers in an apothecary`'s house in Huntingdon--and the other,
to be chaplain to one called the Lady Molesworth, as I remember.

Here was some prospect of preferment, and that before I heard of Wandsworth school,
or knew anything of it.
So that if I had been so greedy of mammon as our
author`'s charity would seem to represent me,
I might have smothered my convictions and turned back into Egypt again.
But blessed be God, who preserved me in that day, and kept me low before him!
I trusted to his kind providence, who knew the sincerity of my heart;
and I chose rather to be poor and destitute with a good conscience,
than to have all the riches and honours of the world without it.
I had found the pearl of great price, and I knew I must sell all to purchase it.
Truth was my greatest treasure; that was my chiefest joy: '`For,`' as the apostle says,
'`our rejoicing is this, the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom, but by the grace of God,
we have conducted ourselves in the world.`'`"

--

This brief Memoir of Samuel Crisp, considered in connection with the sincerity, humility,
and genuine piety which his Letters, etc., exhibit,
shows that he had begun to build on the one sure Foundation,
and that he bade fair to become a truly serviceable member in the church.
But any hopes of this kind that had been cherished by his contemporary friends,
were only realized to a very limited extent;
inasmuch as it pleased the All-wise Disposer of events
to cut short the thread of his life.
He died of the small-pox, at Stepney aforesaid, on the 7th of the Fourth month, 1704,
aged 34 years.

[.asterism]
'''

=== Letters of Samuel Crisp

[.offset]
+++[+++The three following Letters of Samuel Crisp were written about the year 1702;
the first and second on the occasion of his withdrawing
from the church of England (so called), to join the Society of Friends.
These have passed through several editions together, as a pamphlet.
The third Letter, a copy of which has been kindly transmitted by a Friend,
to the Editor of the present volume, and which, it will be seen,
contains the expression of his religious feelings to a fellow-professor of the Truth,
is now printed for the first time: this, although very short, is not without its value,
showing, as it does, the writer`'s conviction,
that his having so far yielded to apprehended duty,
as to unite in religious fellowship with Friends,
furnished no ground for relaxing in watchfulness,
and diligence in the Christian warfare.]

[.centered]
==== Letter I.

I received a letter from you, the week before last, which was sent by your uncle Bolton:
there were a great many kind expressions in it, and in your sister Clopton`'s likewise.
I acknowledge myself much obliged to you both, and to the whole family,
for many repeated kindnesses; and if my school had not engrossed so much of my time,
I would have taken opportunity to answer my dear friend`'s-letter now,
and upon that account my delay will be the more excusable.

The news you have heard of my late change is really true--I cannot conceal it,
for it is what I glory in--neither was it any prospect
of temporal advantage that induced me to it,
but a sincere love to the truth, and pure regard to my own soul.
Neither can I be sufficiently thankful to God,
that he has let me live to this glorious day,
and not cut me off in the midst of my sins and provocations against him.
He is long-suffering to us, not willing that any should perish,
but that all should come to repentance.
He has brought me off from the forms and shadows of religion, and let me see,
in a more illustrious manner, what is the life and substance of it,
as he found me in some degree faithful to that measure
of light and knowledge he had bestowed on me,
while I was in the communion of the church of England: therefore he was pleased of late,
as I humbly waited upon him,
to make known to me greater and deeper mysteries of his kingdom.
And I can truly say, that I find by daily experience,
as I keep low and retired unto that pure gift which he has planted within me,
things are more and more cleared up to me,
and the truth shines and prevails greatly over the kingdom of darkness;
and if I should now turn my back upon such manifestations as these,
and entangle myself again with the yoke of bondage,
surely I should grieve the Holy Spirit,
so that he might justly withdraw his kind operations,
and never return more to assist and comfort me.
For God is not mocked: religion is a very serious and weighty thing;
repentance and salvation are not to be trifled with;
nor is turning to God to be put off till our own time, leisure, or convenience;
but we must love and cherish the least appearance of Christ,
not slighting or despising the day of small things,
but embrace the first opportunity of following Christ in any of his commands.

When he speaks, it is with such force and authority, that we cannot stand to cavil,
dispute, or ask questions:
for unless we will be so obstinate as to shut our eyes against the sun,
we must needs confess to the truth of his doctrine, and presently strike in with it.
And, therefore,
when for several weeks I had lived more privately and retiredly in London,
than was usual, fasting twice or thrice in a week, and sometimes more,
spending my time in reading the Scriptures and in prayer to God,
this was a good preparation of my mind to receive the truth
which he was then about to make known to me.
I lamented the errors of my past life,
and was desirous to attain a more excellent degree of holiness
than I had discovered in the church of England.
In this religious retirement God knew the breathings of my soul, how sincere I was,
and resigned to him when alone.
I needed him to set me free, and to speak peace and comfort to my soul,
which was grieved and wearied with the burden of my sin:
for though I had strictly conformed myself to the
orders and ceremonies of the church of England,
and had kept myself from running into any great or scandalous enormities,
(the fear of the Almighty preserving me),
yet still I had not that rest and satisfaction in
myself which I desired and greatly longed for.
I found when I had examined my state and condition God-ward,
that things were not right with me.

As for a sober and plausible conduct in the eye of the world,
I knew that was a very easy attainment: a good natural temper,
with the advantage of a liberal education,
will quickly furnish a man with abilities for that;
so that he shall be looked upon as a saint, and very spiritual,
when perhaps in chains of darkness, in the gall of bitterness,
and in the very bond of iniquity.
If this sort of righteousness would have done,
perhaps I might make as fair pretensions that way as some others; but, alas!
I quickly saw the emptiness and unsatisfactoriness of those things:
this is a covering that will not protect or hide us from the wrath of the Almighty,
when he comes to judgment.
It is not a man`'s natural temper, nor his education, that makes him a good Christian:
this is not the righteousness the gospel calls for,
nor is this the "`truth in the inward parts,`" which God requires.
The heart and affections must be cleansed and purified
before we can be acceptable to God;
therefore it was death to me to think of taking up my rest in a formal pretence of holiness,
wherein I yet saw to my grief, abundance of people wrapped themselves,
and slept securely and quietly, dreaming of the felicity of paradise,
as if heaven were now their own,
and they needed not trouble themselves any more about religion.
I could not entertain so dangerous an opinion as this;
for then I should be tempted to take up my rest by the way,
while I was travelling towards the promised land.

I think I made a little progress in a holy life,
and through God`'s assistance I weakened some of my spiritual enemies,
while I lived in the communion of the national church.
I thank my God, I can truly say, while I used those prayers,
I did it with zeal and sincerity, in his fear and dread:
but still I ceased not my earnest supplication to him in private,
that he would show me something mere excellent;
that I might get a complete victory over all my lusts and passions,
and might perfect righteousness before him.
For I found a great many sins and weaknesses daily attending me;
and though I made frequent resolutions to forsake those sins,
yet still the temptation was too strong for me;
so that I had often cause to complain with the apostle, in the bitterness of my soul,
"`O wretched man that I am! who shall deliver me from the body of this death?`"
Who shall set me free, and give me strength to triumph over sin, the world,
and the devil; that I may in everything please God,
and there may not be the least thought, word or motion, gesture or action,
but what is exactly agreeable to his most holy will, as if I saw him standing before me,
and as if I were to be judged by him for the thought of my heart the next moment?
O divine life!
O seraphic soul!
O that I could always stand here! for here is no reflection, no sorrow, no repentance;
but at God`'s right hand there is perfect peace and a river of unspeakable joy.
O that we might imitate the life of Jesus,
and be thoroughly furnished unto every good word and work!
This was the frequent breathing of my soul to God when I was in the country,
but more especially after I had left my new preferment of a chaplain,
and took private lodgings in London.
In this retirement I hope I may say without boasting, I was very devout and religious,
and found great comfort and refreshment in it from the Lord,
who let me see the beauty of holiness: the sweetness that arises from a humbled,
mortified life, was then very pleasant to my taste,
and I rejoiced in it more than in all the delights and pleasures of the world.

And now it pleased God to show me,
that if I would indeed live strictly and holily as becomes the gospel,
then I must leave the communion of the church of England;
but I knew not yet which way to determine myself, nor to what body of men I should join,
who were more orthodox and more regular in their lives.
As for the Quakers (so called), I was so great a stranger to them,
that I had never read any of their books,
nor do I remember that ever I conversed with any
one man of that communion in my whole life.
I think there was one in Foxly, while I was curate there; but I never saw the man,
though I went several times to his house on purpose to talk with him,
and to bring him off from his mad and wild enthusiasm,
as I then ignorantly thought it to be.
As for that way, I knew it was everywhere spoken against:
he that had a mind to appear more witty and ingenious than the rest,
would choose this for the subject of his profane jests and drollery;
with this he makes sport, and diverts the company,
for a Quaker is but another name for a fool or a madman,
and was scarcely ever mentioned but with scorn and contempt.
As for drollery, I confess I was never any great friend to it; but indeed,
if all was true that was laid to the Quakers`' charge,
I thought they were some of the worst people that ever appeared in the world,
and wondered with what face they could call themselves Christians,
since I was told they denied the fundamental articles of the holy faith,
for which I ever bore the highest veneration and esteem.
And notwithstanding, I had always lived at the greatest distance from that people,
and was very zealous in the worship of the church of England,
and upon all occasions would speak very honourably of it,
moreover was content to suffer some few inconveniences upon that account,
(as you very well know), yet my father still looked upon me as inclining to the Quakers;
and some years ago signified to a friend, he was afraid I would become an enthusiast:
and while at Bungan school,
he sent me two books to read that were written against the Quakers;
one of which was John Faldo`'s, who has been sufficiently exposed for it by William Penn.

While I lived, in London, in that private, retired manner I was just now speaking of,
walking very humbly in the sight of God,
and having opportunity to reflect upon my past life,
as I had occasion to be one day at a bookseller`'s shop,
I happened to cast my eye on Barclay`'s works; and having heard in the country,
that he was a man of great account among the Quakers,
I had a mind to see what their principles were,
and what defence they could make for themselves; for sure, thought I,
these people are not so silly and ridiculous, nor maintainers of such horrid opinions,
as the author of The Snake, and some others would make us believe.
I took Barclay home with me, and I read him through in a week`'s time,
save a little treatise at the end, which finding to be very philosophical, I omitted;
but, however,
I soon read enough to convince me of my own blindness and ignorance in the things of God.
There I found a light to break in upon my mind,
which did mightily refresh and comfort me in that poor, low,
and humbled state in which I then was; for indeed I was then,
and had been for a considerable time before, very hungry and thirsty after righteousness;
and therefore I received the truth with all readiness of mind.
It was like balm to my soul, and as showers of rain to the thirsty earth,
which is parched with heat and drought.
This author laid things down so plainly,
and proved them with such ingenuity and dexterity of learning,
and opened the Scriptures so clearly to me, that without standing to cavil, dispute,
raise argument or objection, or consulting with flesh and blood,
I presently resigned myself to God;
and weeping for joy that I had found so great a treasure,
I often thanked him with tears in my eyes for so kind a visitation of his love,
that he was graciously pleased to look towards me when my soul cried after him.
So, though before I was in great doubt and trouble of mind,
not knowing which way to determine myself,
yet now the sun breaking out so powerfully upon me, the clouds were scattered.
I was now fully satisfied in my own mind which way I ought to go,
and to what body of people I should join myself.

So I immediately left the communion of the church of England,
and went to Gracechurch Street Meeting.
After I had read Barclay, I read some other books of that kind,
among which was an excellent piece, though in a small volume, called No Cross, No Crown.
Thus I continued reading and frequenting meetings for several weeks together,
but did not let any one soul know what I was about.
The first man I conversed with was George Whitehead;
and this was several weeks after I began to read Barclay, and frequent +++[+++Friends`']
meetings.
By him I was introduced into more acquaintance; and still the farther I went,
the more I liked their plainness, and the decency and simplicity of their conduct.
They do not use the ceremonies and salutations of the church of England,
but shake hands freely, and converse together as brothers and sisters,
that are sprung of the same royal seed, and made kings and priests unto God.
O the love,
the sweetness and tenderness of affection I have
seen among this people! "`By this,`" says Christ,
"`shall all men know that you are my disciples, if you have love one to another.`"
"`Put on therefore,`" says the apostle, "`as the elect of God, holy and beloved,
bowels of mercy, kindness, humbleness of mind, meekness, long-suffering.`"

Thus, my dear friend, I have given you an account of my proceeding on this affair.
As to my bodily state, if you desire to know what it is,
I may acquaint you that I have my health as well as ever,
and I bless God I have food and raiment sufficient for me,
so that I lack no outward thing;
and I have the necessities and conveniences of life liberally:
let us not burden ourselves with taking care for the vanities and superfluities of it.
Let us possess our vessels in sanctification and honour:
and as we bring our minds into perfect subjection to the whole will of God,
so let us bring our bodies to the most simple and natural way of living;
being content with the fewest things; never studying to gratify our wanton appetites,
nor to follow the customs and humours of men,
but how we may so contract our earthly cares and pleasures,
that we may bring most glory to God, most health and peace to our own souls,
and do most service to the Truth.
And if this be our aim,
certainly a very small portion of the things of this world will suffice us.
Seeing we are Christians,
we should therefore earnestly pursue those things which bring us nearest to God,
and which are most perfective of human nature.
For what is more than a competency, seems to be a burden to a generous,
philosophical soul, which would breathe in a pure vehicle,
that so it may have a quick sense and relish of all blessings,
both of the superior and inferior worlds.

You know, my dear friend, that religion is a very serious thing;
repentance is a great work,
and one precious immortal soul is of more worth than ten thousand perishing worlds,
with all their pomp and glory; therefore let us take courage,
and be valiant for the truth upon the earth--let us not content ourselves
with a name and profession of godliness--let us come to the life and power
of it--let us not despond of getting the victory.
We have a little strength for God:
let us be faithful to him and he will give us more strength,
so that we shall see the enemy of our peace fall before us,
and nothing shall be impossible unto us.
I say, my friend,
let us be faithful to that measure of light and knowledge which God has given us,
to be profited and edified by it in a spiritual life;
and as God sees we are diligent and faithful to work with the strength we have,
he will more and more enlighten us,
so that we shall see to the end of those forms and
shadows of religion wherein we had formerly lived.
But if he sees we are about to take up our rest in those shadows,
that we grow cold and indifferent in the pursuit of holiness,
running out into notions and speculations, and have more mind to dispute,
and to make a show of learning and subtlety, than to lead a holy and devout life,
then it is just with God to leave us in a carnal and polluted state;
to continue yet but in the outward court,
where we may please ourselves with beholding the beauty and ornaments of a worldly sanctuary,
and never witness the veil being taken away,
and that we are brought by the blood of Jesus into the holiest of all,
where alone there is true peace with God, and rest to the weary soul.
I could say much upon this head, if time or leisure would give leave.

As for a particular answer to your letter, I have not time now to give it;
and for the present let this general answer suffice:
and if you will consider things in their pure abstracted nature,
and not allow the prejudice of education to sway you,
but in fear and humility will search out the truth for yourself,
you will find that there needs no other answer to
your letter than what I have already given.
For by waiting upon God, and diligently seeking him,
you will find an answer to it in your own bosom; and this will be much more full, clear,
and satisfactory than I, or any other man living can pretend to give you,
or any other friend who has lovingly written to me; for whom I desire,
with all the sincere-hearted in the church of England,
that they may come to witness the almighty power of God,
to save and redeem them from every yoke:
and that they may clearly see to the end of those things which are abolished,
and come to the enjoyment of spiritual and heavenly things themselves,
is the daily prayer and deep travail of my soul, God knows.
Till I can be more particular, if you please you may communicate this to them,
and let them know that I am well, and thank them for their kind letters.
Let us remember to pray for one another with all fervency,
that we may stand perfect in the whole will of God.
Amen, says my soul.

[.signed-section-closing]
I am your most affectionate friend and servant in Jesus,

[.signed-section-signature]
Samuel Crisp.

[.centered]
==== Letter II.

[.salutation]
My dear friend,

I lately received a kind and brotherly letter from you,
for which I return you many thanks.
I am now in the communion of the people called Quakers;
and I have cause to bless God for this happy change of my life.
I am, through mercy, brought off from the shadow of religion,
and am pressing forward to get acquaintance with the quickening power, life,
and virtue of it, that I may be a Christian indeed,
and not in the name and profession only.
I had a great while talked and discoursed of holiness,
but did not understand what it was to walk with God, to live and dwell in him.
Perhaps, indeed, some may think I made a fair show of piety when I was with you;
but, alas!
I was deeply sensible of my own faults and miscarriages; and I resolved,
through God`'s assistance,
to inquire after something more noble and excellent than I had discovered in that state:
and blessed be his name forever, that God has answered the cry of my soul,
and let me see a people, that are hated and despised by the world, but are dear to him;
for he has revealed to them the mysteries of the kingdom;
he has carried them upon eagles`' wings, and cherished them as the apple of his eye.

As for me, I have been yet but in the outward court,
and far short of that truth and righteousness that
is taught and practised among this people;
for they are come within the holiest of all--they are come into
a near communion with God--to behold the cherubims of glory that
cover the mercy seat--to be fed with the true manna.
These are mysteries that are revealed unto the meek and lowly; but the haughty, insolent,
and profane cannot come near them, nor taste of the sweetness nor comfort of them.
Indeed the formal, traditional sort of people of the world may talk of these things,
as they have heard them from others,
and in their sober moments may have some faint glimmerings that way;
but to be come to the real and inward enjoyment of them, they can no more pretend,
than to work the greatest impossibilities: all their wit, and subtlety, and learning,
cannot reach higher to handle of the word of life;
this is peculiar only to those who are content to forsake all,
and become fools for Christ.
They are those who are in a good temper to receive
and cooperate with the influences of the Holy Spirit,
and have seen the emptiness and vanity of all those
things that are so much admired by the world.
The schools and universities, and learned doctors, and great rabbis,
have not profited me; they are ravened from the Spirit of God,
and gone out into their own notions and speculations, thinking thereby to search out God,
and comprehend the truth.
Alas! the mysteries of the kingdom are far out of their reach in their carnal minds;
they weary themselves in vain; the vulture`'s eye cannot pierce into these secrets;
all the great critics, scholars, and philosophers of the world,
are fools in these things.
They are wearying themselves to find the deep things of our God,
studying and racking their heads,
tossing and tumbling to and fro like a wild bull in a net,
that knows not which way to disentangle himself: the more he struggles,
the weaker he grows and the faster he is bound; so the more these vain talkers read,
the more they write, the more they cavil and dispute, the farther they are from God,
and the more they declare their hatred and enmity to the spirit of Christ,
and to the simplicity of the gospel.

I have been a long time weary of the folly and impertinency of these men,
and chiefly the celebrated fathers of the church, as they call them:
the councils and synods of old are now of very small account with me.
I am not ashamed to sit under the teachings of women and mechanics,
howsoever they may seem in the eye of the world; for they teach me more Christianity,
and instruct me more perfectly in a divine life, than all the studied,
elaborate sermons and discourses that ever I heard at the universities or since;
their words are with power--they are mightily assisted with the spirit
of God--they speak with majesty and authority--and there is a native beauty,
clearness, and solidity of expression, that shines through their discourses,
which is sufficient to answer that groundless calumny, namely,
that the Quakers`' preaching is nonsense, and nobody can understand them.
This I have heard often refuted by many living testimonies;
so that I do rather think them the best wits, and the most ingenious people in the world;
for they employ their parts and learning in the fear of God, to his glory and service,
and to promote the true interest of mankind.

As for the little jests, wittiness, and vain pedantry of the age,
which I know the world has esteem for,
(and nothing will please but what abounds with such fooleries); I say,
if the Quakers be deficient in any of these, it is not for lack of abilities,
or because they have less wit than other men,
but because they have more prudence and wisdom to govern it;
and that is the reason why they avoid such childish vanities,
which are so freely used and indulged in by others, to the great dishonour of God,
and the Christian religion.
Therefore because they do not seek to please a wanton age,
and make people laugh and be merry, nor to entertain that carnal,
airy mind with pleasant stories, fine notions, and witty expressions of natural things;
from there it is that they have been shamefully traduced by the world,
as the most ignorant, blind,
and foolish people that ever made any profession of religion:
and yet this is the people to whom I have now joined myself in a sincere love to truth,
God knows.
I glory more in this fellowship and acquaintance with these lambs of Christ,
than if I were related to the greatest kings, lords, and potentates upon the earth.
Oftentimes has my spirit been refreshed with theirs,
when we have met together to wait upon God;
and my soul still longs and pants more and more to be filled with these divine comforts.
He is ready always to pour down blessings upon us,
if we would qualify ourselves for the reception of them;
if we would put away vain thoughts, which cloud and darken the mind,
and so hinder the favourable influences and irradiations of heaven.
And since it has pleased God to visit me of late,
and to make known to me excellent things in righteousness,
he alone is to have the praise and glory of all;
and now I freely resign myself to the conduct of the blessed Spirit.

Now let the truth prosper; now let it run and be glorified in the earth;
let it shine out in its full lustre,
to the terror and confusion of all the enemies thereof,
and to the reviving of the souls of the hungry and thirsty, who are ready to faint,
waiting for and expecting the consolation of Israel,
until the time of refreshment comes from the presence of the Lord;
who will open a fountain for Judah and Jerusalem, so that rivers shall run in dry places:
there will he speak peace to his people.
And after they have sat silent a little while in the dust,
suffering patiently the chastening rod of his love to pass over them,
he shall then comfort the daughter of Zion, and say, "`Arise, you afflicted,
and weep and mourn no more, but put on your beautiful garments,
O Jerusalem! raise your head, uncover your face, and gird up your loins with strength;
see the day break, and the morning spread itself upon the mountains;
now the sorrowful nights of affliction are gone over, the clouds are scattered and gone,
the sun is risen in its brightness, and now joy and peace shall be multiplied;
in a little wrath I hid my face from you for a moment,
but with everlasting kindness will I have mercy on you, says the Lord your Redeemer.`"
O! let us wait, in humility of soul and tenderness of heart, before the Lord,
that we may witness this great change and salvation wrought in us and for us;
that the Scripture may be no more a sealed book to us,
but that we may feel the precious truth therein recorded,
to be fulfilled in our own particulars.
Then we shall never be weary of praying, and reading the Holy Scriptures;
we shall never be loath or unwilling to come into God`'s presence: for his love,
and the sweetness of his ointment,
will draw and allure us to dwell always under his canopy,
that we may feel life and power to flow from him,
who is the ocean that supplies all the needs of the children of men.
And how shall we come to taste that heavenly banquet which he has prepared for us,
that we may eat and drink at his table, and that our souls may delight in fatness--I say,
how shall we attain to this, but by a strict and mortified life?
Certainly the more we retire from worldly joys,
and empty ourselves of earthly comforts and false delights,
the fitter we shall be to receive those that are spiritual and heavenly;
and not only to receive and rejoice in them for a time,
but to live and dwell in them forever.
For this is the life of Jesus; and here the kingdom of God reigns in the heart and soul,
by which it is changed from glory to glory, even as by the Spirit of the Lord.

And now I would ask all the wise and prudent, all the rich,
all the noble and learned men of the world, what they think of these things?
Whether this is to be learned in their courts and palaces?
Or whether any of the great scholars and universities in Christendom
can furnish us with such a system of divinity as this?
No; they hate it and despise it; and instead of a sober answer to my query,
they return scoffs and contempt.
"`This is canting,`" they say,--"`an idle dream,
and forged chimera of his own brain;`" and a great many
more opprobrious names they have for such inquiries as these.
Sometimes perhaps they will soften the expression with a hypocritical show,
will pretend to pity me, calling it an unhappy effect of melancholy,
and too much retirement from the world;
and this they think too much condescension--that I ought to think
myself beholden to them for giving it so mild a character;
for at other times they deal more sharply, and say confidently that it is madness,
delusion, witchcraft, and diabolical enthusiasm.
But I am content to lie under all these odious imputations from the world,
knowing very well, that better men than I, have suffered the same things before me,
and do at this present time.
As for my enemies, I can truly say, I thank God I pity them and pray for them:
they do not hurt me, but themselves.

And now my dear friend, before I conclude,
allow me a little to speak of your present circumstances; for as God knows,
my bowels yearn towards you in the tender love of Jesus,
I suppose you are now where I left you, viz, with the lord Richardson, (so called),
in the capacity of a chaplain; an office which I have had a little experience of myself,
since I last saw you; but was quickly so weary of that servile yoke,
so unworthy of that holy function I bore,
that in ten days`' time I quitted my new preferment,
and left it more free than ever I undertook it.
What peace or satisfaction you can have in such kind of employment, I know not;
for my part I could find none;
my soul was grieved and burdened every day with seeing and hearing their evil deeds,
beholding their vanities and excesses; this was a sword to my soul and spirit,
it wounded me very deep: and I do solemnly profess,
I had rather beg my bread from door to door, than to live in the like bondage again,
where I must be obliged to such ceremonies and formalities,--to
flatter men in their sins,--to cry,
"`peace, peace;`"--and to sew pillows under the armholes of delicate people,
who can never bear the least check or frown;
but expect the mercenary priest should always laugh or smile in their faces,
even when he sees plainly they are going to hell and destruction.
And yet I must tell you,
the family I was in was looked upon as one of the most sober and regular,
as the world goes now; and I must needs say, I did not leave them for any drinking,
gaming, or swearing, that I perceived among them; as to all these filthy,
scandalous practices, as far as I could see, they were blameless:
but yet I saw their hearts were not right,
for they were lovers of pleasure more than lovers of God; and you know that he or they,
let them be great or small, if they live in pleasures, grow fat,
and wanton against Christ; such persons are dead while they live.
I say, whatever their faith, or principles, or professions may be,
yet in religion they are dead.
I shall say no more, but hasten to a conclusion.

If you desire a particular account of my convincement,
you may see it in a letter I wrote lately to Richard Lake, junior,
wherein I gave him a fair and true relation of my proceedings in that
matter--what steps I took--and how God did graciously assist me,
when he had raised in me sincere desires and inquiries after truth and holiness.
Dear friend, I have no more at present, but to let you know,
I do most heartily pray for you, that you may consider things without prejudice,
and not allow any of the temptations and allurements
of the world to draw your mind from God,
and to hinder you in your pursuit of holiness.
He that loves father or mother, brother or sister,
or any of the endearments of this world, more than Christ, is not worthy of him:
but if you will come into communion with Christ,
and follow the guidance of his light and spirit,
O what a blessed and happy rest shall you find to your soul!
O what rivers of living waters will spring up in you! of which you may drink freely,
and praise God for all his mercies and benefits.
That you may indeed come to such spiritual enjoyments and refreshments as these,
is the sincere desire of

[.signed-section-closing]
Your loving and affectionate friend,

[.signed-section-signature]
Samuel Crisp.

[.centered]
==== Letter III.

[.signed-section-context-open]
Leeds, Sixth month 7th, 1702.

[.salutation]
Loving friend, G. Paxton,^
footnote:[A Friend who resided in Durham.]

These may acquaint you,
that last fourth-day was a week since I got well to my journey`'s end.
But though my body rests as to the outward,
yet I still feel a necessity to continue my inward,
spiritual travel towards the new Jerusalem, the heavenly Canaan,
where my soul may be satiated with everlasting and unchangeable felicity.
I must still keep on my watch,
that the enemy of my soul may not at any time take an advantage against me:
I must still stand upon my guard, go on in the Lamb`'s warfare,
and diligently pursue such things as may make my calling and election sure:
and this I think is the state of every Christian, so long as he sojourns in this world.
Perfect and complete rest and peace are only to be
expected when we have laid aside these mortal,
frail bodies,
and shall enter those mansions of glory that Christ our Head has prepared for us.
But if we would reign with him in another world,
we must suffer with him in this--if we would wear the Crown,
we must first bear the Cross; if we would be conquerors,
we must fight--if we would win the prize, we must not be cool and indifferent,
but exert all our strength in the Christian race--in short, if we would be perfect,
we must sell all, part with all our lovers, and +++[+++be willing to]
sacrifice all the nearest and dearest enjoyments,
that we have in this world +++[+++when called for]:
this is self-denial--this is mortification indeed--and this is the repentance unto life,
never to be repented of.
My love to your uncle and Friends.

[.signed-section-closing]
I am your loving and affectionate friend,

[.signed-section-signature]
Samuel Crisp.

=== Extracts from Samuel Crisp`'s Vindication of the People Called Quakers

[.offset]
+++[+++The first of the three following pieces is extracted
from the Preface to Samuel Crisp`'s Vindication,
the next from the Treatise itself, and the remaining one from the Appendix to it.
It is believed that the weighty counsel, sound doctrine,
and instructive remarks which these Extracts contain,
will commend them to the cordial acceptance of the serious reader.]

==== A Plea for the Truth, and an Earnest Exhortation to be Found Walking Therein.

[quote.scripture, , Jer. 6:16]
____
Stand in the ways and see, and ask for the old paths, where is the good way,
and walk therein, and you shall find rest for your souls.
____

[.salutation]
Reader,

I desire you would be serious and unbiased in the reading of what I here present
to your view--so may you reap benefit and advantage by it to your soul.
The noise and clamour against the Quakers,
has of late years been carried on and promoted with great diligence by their adversaries;
insomuch as few, I think, who converse with the world, can be ignorant of it.
This gave me occasion to inquire into their principles;
and that I might not take things upon trust,
or believe the report of others concerning them,
I was willing to see for myself--to read and consult their own authors.
To this I applied myself with great seriousness;
desiring of the Lord in great humility and bowedness of soul,
that he would open my understanding in the great things of his law,
and that if the truth was among the Quakers, I might,
without consulting with flesh and blood, join myself to that people,
however slighted and despised I might be by the world for so doing.
It was peace with God I lacked; and in comparison of that,
I looked upon all other things as dross and dung.

I had been always brought up in the national way of worship,
and had been strict and punctual in the rites and
ceremonies of the church of England beyond many;
but yet I found all that would not do my business; the seed was oppressed,
and death reigned under all those forms and specious appearances of godliness.
It was an easy matter to talk, and go the round of my devotions;
but I lacked strength and power to overcome my sins and corruptions.
There was a cry raised in my soul after righteousness and truth;
and this I found all my outward observations could not give me,
for the kingdom of God is within men, though I was seeking for it abroad,
doating upon shadows.
And thus was I diverted from the pursuit of the knowledge of the truth, as it is in Jesus.
I lived in darkness and ignorance of the true and saving knowledge of God,
notwithstanding my high pretensions.
But it has pleased God to rend the veil, to disperse the clouds,
and scatter the mists and fogs, in a good measure, blessed be his name.

Know, reader, that there is a people in this age, who have paid something for religion;
and they will not be put off with shams and pretences,
nor decoyed by the wiles of the enemy: they are not easily to be imposed upon,
in the great things that concern their everlasting peace: they cannot bow to images,
nor satisfy themselves with the husks and formalities of religion,
but labour to come into the life of holiness and the real practice of virtue;
whom neither smiles nor frowns can prevail with to forsake the truth.
These the devil envies, and to render them odious, he paints them out in black colours.
To be sure, in his account,
they are fools and madmen--fanatics I`'ll warrant
you--schismatics--heretics--a dangerous sort of people:
Sirs, look to yourselves, and as you love your souls,
beware of the infection of Quakerism.
This is the common language, when people do not please him; but if they are tame,
and easy to his insinuations, if they can rest in a form,
and dwell upon words and notions,
then he reigns in peace--his kingdom is quiet--no hard names then.

Well, reader, what I said before, I repeat now--it concerns you to be serious,
and to weigh things with a clear and disinterested mind.
If you will serve God, you must take courage and break loose from the world:
if you will come to Christ, you shall find true riches,
and a fountain of inexpressible joy.
If you die with Christ, you shall live; if you suffer with him in this vain,
transitory world, you shall reign with him in glory forever.
Look not at your own weakness, but look unto God, whose grace is sufficient for you;
his strength is magnified in our weakness.
Let not then the cross discourage you, but take it up,
and in meekness and patience bear it after Jesus,
who for the joy that was set before him, endured the cross, despising the shame,
and is set down at the right hand of the throne of the majesty in the heavens.
Strip yourself from the creatures; wean your affections from the world;
strengthen your hand in God; cleave steadfastly unto him; make him your friend,
and then you needst not care who is your enemy;
all the rage of men and devils can never hurt you.
Hearken unto God; obey his voice; mind the teachings of his Holy Spirit;
give up yourself entirely to the conduct of it, for its ways are ways of pleasantness,
and all its paths are peace.
This is that Comforter which is given to lead us into all truth:
blessed are all those that are taught and led by it;
they see their way--it is made plain, and shines more and more unto the perfect day.
Trust not to uncertainties; put not off your repentance;
delay not the time of returning to God.
How do you know you shall live an hour longer?
Are all your accounts fair and clear?
Are you ready to depart, if God should call you before tomorrow morning?

Reader, once more I say--it concerns you to be serious; for the day of God hastens,
wherein all false coverings shall be rent off; fear shall take hold on the hypocrites,
as sorrow upon a woman in travail, and they shall not escape.
A name and profession of Christianity without the life and power of it,
will then stand in very little stead; it will be a terrible day,
who shall be able to stand in it!
Certainly none of the hypocrites, and shufflers, and vain talkers,
and disputers of this world, and empty notionists, and time-servers, and men-pleasers;
no, they will be all swept away, as chaff before the wind.
"`For behold the day comes that shall burn as an oven; and all the proud, yes,
and all that do wickedly, shall be stubble: and the day that comes shall burn them up,
says the Lord of Hosts,
that it shall leave them neither root nor branch.`"--Mal. 4:1.
And therefore now is the accepted time,
prize it; now is the day of salvation.

Know, reader, that by the grace of God, you are capable of great attainments;
true faith will remove mountains; by that you may escape the pollutions of the world,
and come clean out of Babylon and Egypt,
and all such things as would let or hinder you in your Christian race.
Why then should we trifle away our precious minutes?
Why should we die short of true happiness?
Let the time past surface us, to have wrought the will of the Gentiles,
serving various lusts and pleasures, and walking in the vanity of our minds.
God has borne long with us; his mercy and lovingkindness has been great;
let us provoke him no longer,
but instantly return to him and humble our souls before him.
This is the labour and travail of my soul, God knows,
desiring that all men might be saved and come to
the knowledge of the truth as it is in Jesus.
O that all would taste and see how gracious he is!
If they would wait upon him in silence, with their minds retired from the world,
and stayed upon him, they may come to see wonderful things in righteousness;
the mysteries of God`'s kingdom should be opened and revealed to them,
yes things which were kept secret from the foundation of the world.
Such should find true peace and rest to their souls;
they should find strength administered according to their several needs,
and grace to help in time of need; yes,
they should go from strength to strength and grow in grace daily, as the Apostle said,
Eph. 4:13; "`till we all come in the unity of the faith,
and of the knowledge of the Son of God unto a perfect man,
unto the measure of the stature of the fulness of Christ:`" which, reader,
that we may all come to know, witness and experience in ourselves,
is the earnest supplication and prayer of your hearty well-wisher and sincere friend,
to serve you in the Truth.

[.signed-section-signature]
Samuel Crisp.

==== On Divine Worship, Gospel Ministry, and the True Church.

[quote.scripture, , John 4:24]
____
God is a Spirit; and they that worship him,
must worship him in spirit and in truth.
____

Our Christian belief is, that every man ought to wait upon God,
in the measure of his own good Spirit; that he is to follow its motions,
observe its counsels, and make it the great rule and guide of his life; and we say,
as men wait in this and are led and governed by this, so, and not otherwise,
are they accepted and approved in the sight of God.
For this, and this only, can work all acceptable works in us, and for us.
"`Walk in the Spirit, and you shall not fulfill the lusts of the flesh.`" Gal. 5:16.
"`For as many as are led by the Spirit of God, they are the sons of God.`" Rom. 8:14.
In the performance of all religious worship,
we say there is especial need that men should wait upon God,
in the gift of his own Spirit, to feel the conduct and assistance of it;
for this is the salt of the sacrifice, it is this gives savour and life to every duty,
it is this must make known our needs to us,
and instruct us how to apply ourselves to God for suitable relief.
The apostle of the Gentiles is excellent in this:
Rom. 8:26-27,--"`Likewise the Spirit also helps
our infirmities;--and he that searches the hearts,
knows what is the mind of the Spirit,
because he makes intercession for the saints according to the will of God.`"
God is to be worshipped in spirit and in truth; and we wait upon him in silence,
that we may be enabled to perform this worship and service,
believing that his Spirit will help and teach us to pray,
better than all directories and common-prayer books.
Shall we for this be ridiculed?
and because we are tender of the righteous seed of light and life in ourselves and others,
observing what the apostle enjoins, not to quench the Spirit nor despise prophesyings,
must we therefore be called fanatics and enthusiasts?

It is not men`'s running over their prayers by heart, or reading them out of a book,
or undertaking to pray or preach by the strength of their own reason and natural faculties,
that finds acceptance with God.
None of these can be said to be that spiritual worship and
service which God calls for in the days of the Gospel,
now that he has sent forth the Spirit of his Son into our hearts,
whereby we cry Abba Father: not now, I say,
when he has poured forth his Spirit upon sons and daughters;
so that they can and must prophesy; not now,
when God has so clearly revealed himself to the world, and told us expressly by his Son,
that he is a Spirit; that the true worshippers shall worship him in spirit and in truth;
and that he seeks such to worship him.
These are Gospel days;
this is the last and most glorious dispensation that shall ever be in the world;
now God calls for a more than ordinary strictness and purity of life.
The times of ignorance, it is said, God winked at;
but now he commands all men everywhere to repent; to leave off their dead forms,
their empty ceremonies and hypocritical will-worship,
a worship which they can go about in their own time,
begin and finish it when they please.
Here many are making a profession of religion and godliness outwardly,
going on in a round of bodily exercises, and pretended devotions,
from one year`'s end to another, and yet are destitute of the inward,
experimental knowledge of Jesus Christ.

But blessed be God forever, that he has in this generation,
made bare his arm in a wonderful manner, and brought a remnant near to himself:
they have seen to an end of types and shadows, and are come to Christ,
the life and substance, and to the one spiritual baptism,
that purges the conscience from dead works, to serve the living God.
And they are come to the true supper,
and inward communion of the body and blood of Christ; where they feed daily at his table,
and eat of that bread that came down from heaven,
which nourishes the soul unto eternal life.
These are brought off from all the world`'s carnal and literal teachers,
and are come to the ministration of the Spirit, and the teachings of Christ Jesus,
who is their Prophet, Priest, and King, the only true Shepherd and Bishop of their souls.
These are come to a true silence, and ceasing from all their own words;
they wait for the arising of that Divine Power and Life which shall render
their service accepted of God and useful and beneficial to men.
They preach and pray as the Spirit helps them.
They observe Christ`'s rule and precept, which is, to watch and pray; plainly showing,
that before men pray, they should watch; that is, retire in their minds,
and wait upon God, that they may "`serve him acceptably, with reverence and godly fear.
For (as the apostle says) our God is a consuming fire.`"
Those who rush hastily into his presence, without due preparation and watchfulness,
they offer the sacrifice of fools;
they do not come up with acceptance on God`'s altar.--Isa.
9:7. It is said of Nadab and Abihu,
that "`they offered strange fire before the Lord, which he commanded them not.
And there went out fire from the Lord, and devoured them,
and they died before the Lord.`"--Lev. 10:1-2.

Let the ungodly and uncircumcised priests and people of the world,
who on all occasions are so full of their prayers and devotions, consider this:
they would,
I am confident be ashamed to appear in that posture before some of their superiors,
wherein they many times appear before God.
But, as I said before, they who know God rightly,
have learned to wait upon him in the silence of all flesh.
"`Without me,`" says Christ, "`you can do nothing.`"
Being sensible of this, they have learned to bow and humble themselves before God;
not daring to open their mouths, or speak a word,
but as God is pleased to make known to them the mysteries of his kingdom,
to prepare a sacrifice for himself,
and to touch their lips with a live coal from the altar.
When the well springs up, then they can sing unto it.--Num. 21:17. When God opens,
none can shut; and when he shuts none can open.
These wait, as the apostles at Jerusalem, to receive power from on high;
when God bids them speak,
they must speak--they may neither add to +++[+++that which is given them,]
nor diminish from it.
They must not quench the Spirit, nor despise prophesyings.--1 Thess. 5:19-20.

This is our Christian belief, with respect to the worship of God,
and the solemn offices of religion, such as praying and preaching.
And by the places cited, it may appear to every impartial eye,
that these are no new lights or upstart notions, but agreeable to Holy Scripture,
and the practice of the primitive Christians; to whose blessed example,
holy and pious life, we desire in all things to conform ourselves.

The church of God is the pillar and ground of Truth:
it is built upon the foundation of the apostles and prophets,
Jesus Christ himself being the chief corner-stone.
The church of God consists of living stones; they are built up a spiritual house,
a holy priesthood, to offer up spiritual sacrifices, acceptable to God by Jesus Christ;
they are a chosen generation, a royal priesthood, a holy nation, a peculiar people,
who in life and conduct,
show forth the praises of Him who has called them out of darkness,
into his marvellous light.
This is a glorious church, not having spot or wrinkle or any such thing,
but holy and without blemish.
This is the true church and true religion,
which we desire all people would seriously consider and diligently press after.

[.old-style]
=== A Warning given to the present generation, / to consider their ways and turn unto the Lord; / wherein they are reminded of the late dreadful tempest of wind.

[quote.scripture, , Ps. 135:6-7]
____
Whatsoever the Lord pleased, that did he in heaven, and in earth, in the seas,
and all deep places.
He causes the vapours to ascend from the ends of the earth;
he makes lightnings for the rain;
he brings the wind out of his treasuries.
____

How gloriously has the Truth broken forth in this latter age of the world,
and how has England been favoured with the bright sunshine of the gospel,
and the revelation of eternal truths I And how has
God waited with much long-suffering and patience,
to gather this nation to himself!
How has the word of the Lord been proclaimed in towns and cities,
and that with much dread, and great majesty and power!
And how has the Lord stretched out his hand to the inhabitants of this island,
day after day and year after year;
that if by any means he might gather them in the arms of his love, and bless them,
and make this land as a garden of pleasant plants, an eternal excellency,
the joy of the whole earth!
But O, how ill have many requited him for his kindness, and mercy, and long-suffering!
How have they hardened their hearts, and rebelled against his Holy Spirit,
and slighted the overtures of peace and reconciliation!
How have they abused his servants,
and shamefully treated those that came purely in love to their souls,
and sought neither their silver nor gold, but their eternal welfare;
and were willing to leave their families, friends and relations,
and travel many hundreds of miles to invite others to come in and partake with them,
in the glorious communion and fellowship of the saints in light!
And O how shily and disdainfully have the poor worldlings and their blind priests--who
were settled in the earth--looked upon these innocent servants of the Lord!
And what an outcry have they raised against them! treating them as rogues and vagabonds,
of whom yet the world was not worthy, and by calling them seducers, and heretics,
and blasphemers, and Jesuits, and fools, and madmen,
and anything that malice or ignorance could suggest!
And O what flouts and jeers, and stripes, and knocks, and bruises, have they met with,
for their obedience to the Lord! and all this from
a sort of men that called themselves Christians;
from whose profession one would expect better things at their hands.

And how ill both priests and people have requited the servants of the Lord,
for their testimony against the works of darkness!
Surely God will judge for these things.
And notwithstanding the gospel has been so fully
and demonstratively preached in this nation,
yet how do sin and wickedness, injustice and oppression, fraud and violence,
and all manner of abominations, run down the streets of towns, cities and villages,
like a mighty stream!
How madly and desperately do many lead their lives!
What prodigious excess, and pride, and vanity, and superfluity,
are found among the inhabitants of England!
How do ungodly men devour the creation, and spend it upon their lusts,
and weary themselves to commit iniquity!
They bid defiance to all religion, and cast off all seriousness; they rant and swear,
dance and sing, and fill the land with oaths and blasphemies.
They wallow in pleasures, and indulge themselves in ease and softness perpetually;
and are not valiant for the truth upon the earth,
but live enslaved to the devil`'s kingdom.
They speak every man vanity with his neighbour: and as for lying, and flattery,
hypocrisy and deceit, there is no end of them.
Hypocrites and formalists, shufflers and mammonists spare one another,
wink at one another, daub one another,
and bolster up one another in their unrighteous and ungodly ways and practices.
And such God hates; and his fierce wrath will be manifest against them,
except they repent.
What a deep sleep and prodigious carelessness possesses the minds of such men!
What do they study?
What do they regard?
Nothing but to satisfy their lusts, and please themselves.
As for religion and meekness, sobriety and virtue, they are bantered and ridiculed,
hissed and spurned at, and kicked off the stage of the world.
Honesty, truth, and plain-dealing, find no room in men`'s hearts;
they cannot bear to be told of their faults; daub them over and wink at them,
and then you please them.
The consideration of these things cannot but wound any Christian heart.

Ah sinful nation! a people laden with iniquity!
The Lord, in mercy, put a stop to this torrent of wickedness!
The Lord touch every soul with a deep sense of their provocations,
and make them truly penitent,
and incline their hearts to the serious study and practice of holiness!
May the great men and rulers of the earth make it their business,
both by their example and authority, to check vice and wickedness,
and discourage and suppress all profaneness, debauchery and immorality.
They may be instruments of much good in their generation,
if they would zealously and impartially exercise
that power which they have in their hands;
otherwise they cannot escape,
but their condemnation will be great in the day of the Lord, O,
may the judgments of the Lord,
awaken people to a speedy and timely repentance! that they may learn righteousness,
and know the things that belong to their everlasting peace,
before they be hid from their eyes, and the wrath of God break forth against them,
to their utter desolation.

What do people think of the late great stormy wind^
footnote:[This was a truly awful visitation:
the following account of it is extracted from some authentic published
Records of Remarkable Events:
{footnote-paragraph-split}
"`One of the most terrible storms of wind that was perhaps ever known in England,
occurred on the 26th of November, 1703, attended with vivid flashes of lightning.
It commenced about ten o`'clock at night,
and continued to rage with extreme violence till seven the next morning,
when it gradually moderated.
So tremendous were its effects, that people feared a total wreck of nature.
{footnote-paragraph-split}
Although the devastation was particularly afflictive in the Metropolis,
yet every part of the kingdom experienced more or less of its ravages.
The damage sustained within the city alone, was estimated at two millions sterling;
besides vast loss in other parts of the Metropolis.
Upwards of two thousand stacks of chimneys were blown down;
and the streets covered with broken tiles and slates from the roofs of houses.
The lead on the tops of several churches, was rolled up like skins of parchment;
and at Westminster Abbey, Christ`'s Hospital, St. Andrew`'s Holborn,
and many other places, it was carried off from the buildings.
Several houses near Moorfields, were levelled with the ground;
as were about twenty others in the outparts, together with a great number of brick walls,
and gable ends of houses.
Twenty-one persons were killed by the fall of the ruins,
and about one hundred others greatly injured.
All the ships in the river Thames, between London Bridge and Limehouse, except four,
were forced from their moorings and thrown on shore;
upwards of four hundred wherries were entirely lost;
more than sixty barges were driven foul of London Bridge,
and as many more were either sunk or staved between the Bridge and Hammersmith:
these events were also attended with the loss of many lives.
{footnote-paragraph-split}
The loss sustained at Bristol,
was computed at 200,000. But the destruction at sea far exceeded that on land:
for in this dismal night, twelve men-of-war,
with upwards of eighteen hundred men on board, perished within sight of their own shore;
great numbers of merchantmen were also lost: and in fact the entire damage was so great,
that its amount exceeded all computation.`"]--the most dreadful
calamity of the kind perhaps that ever afflicted this nation?
How were thousands distressed then, both by sea and land!
What a consternation was upon the minds of people--fear without and fear within!
And what weeping, and crying, and lamentation, was there in many places!
And how were many cut to the heart, and knew not what to say, nor what to do!
For the hand of the Lord was upon them, and the arrows of the Almighty wounded them;
and they knew not which way to escape,
nor where to hide themselves from the fierceness of his indignation,
who was come and coming to shake terribly the inhabitants of the earth.
And then many a rotten, hypocritical heart, I believe, was ripped up,
and the false covering torn, off; men saw their shortness in many things,
and were ready to cry to the Lord for mercy; wished they had lived better lives,
and that instead of talking of Christianity, they had practised it.

But alas, how soon are these things forgotten!
And what amendment or reformation do we see in men`'s lives?
He that was a hypocrite and a formalist, and a time-server and a hireling last year,
for aught I see, is so still.
He that was bitter, passionate, peevish, uncharitable, covetous,
selfish and earthly-minded, and even without natural affection, is so still.
He that was scraping and raking up wealth then, is doing so still.
He that was puffed up with pride, and a loose liver, and a libertine,
and strutted about with his sword and long powdered wig then, is and does so still.
She that was dressed _a-la-mode_ then, and could patch, and paint, and take her pleasure,
and live in wantonness upon the earth, does so still.
O how the lusts of the flesh, the lust of the eyes, and the pride of life,
abound among them!
And the priest drives on his trade, and looks for his gain from his quarter;
and his wife and children must be in the proud fashions,
or else what will the neighbours say of him?
But how to rebuke vice sharply and boldly, and set a good example, he knows not;
the poor man has no heart to it, he fears it will not be for his interest.
And so he that was at ease in a dry and empty and fruitless profession,
thinks himself secure still; the old clothes go on,
and he runs the round of formality and hypocrisy.
And the careless daughters still walk about the streets, with stretched out necks,
and their monstrous head-dresses, mincing as they go, so delicate,
as if the ground were not good enough for them to tread upon.

Is this our improvement upon God`'s judgments--our mourning in sackcloth and ashes?
Oh the incorrigibleness of mankind!
He that could fight and swear, and curse and damn, and revel and be drunk,
and cheat and lie last year, for aught I see, can do so still.
And few are humbled under the hand of the Lord as they ought to be: few mourn in secret,
and turn unto the Lord, and seriously lay things to heart, and consider their latter end.
But they go on, every man in his own way, and set up their idols in their hearts,
to commit abomination therewith.
And the wanton, the voluptuary, and the ambitious, pursue their pleasures and delights,
and worldly interests, with as much eagerness and resolution as ever.
And is this a time, now when God has so eminently signalized his displeasure against us,
to plead for sin and imperfection, and strengthen the bands of wickedness,
and for any to stir up persecution?
Surely we way find other work to do.
What! are not the sins of this nation great enough?
Is this a time to wink and spare, and daub and bolster up men in their sins?
What! shall profaneness and the most scandalous immoralities still go unpunished?
And shall the play-house still be permitted to laugh at religion,
and droll upon everything that is serious, to debauch the age,
and propagate a stock of atheists and libertines?
Surely these things are not consistent with Christianity:
and truly whatever men may talk, nothing short of this,
is like to avert those judgments that seem to hang over our heads.
How it may please God to visit us the next time, we know not:
but surely if we still go on in our impenitence and stiff-neckedness,
it may be just with God to be more severe with us.

And now, that the Gospel may prosper, and righteousness increase, the church flourish,
and truth and peace, love and good works take place in the earth,
is the desire of my soul.

[.signed-section-context-close]
The 15th of Second month, (called April), 1704.
